import { record } from '../schema.js'
import { eraDossiers } from './dossiers.js'

const eraRecords = [
  record({
    id: 'grande-guerra',
    name: 'I — A Grande Guerra',
    subtitle: 'A ruptura do reino indiviso',
    summary: 'A disputa entre os três herdeiros de Edric Averen dividiu as Doze Legiões e converteu uma sucessão em cem anos de guerra.',
    description: 'Quando Edric Averen morreu sem declarar um sucessor, seus filhos exigiram a Coroa Una com argumentos igualmente frágeis. As legiões escolheram senhores, celeiros viraram fortalezas e antigas estradas foram quebradas para deter exércitos. O conflito encerrou a ideia de um Avernor governado por uma só vontade e deixou fronteiras que ainda orientam impostos, dialetos e ressentimentos.',
    causes: ['Morte de Edric Averen sem sucessor declarado', 'Pretensões incompatíveis de Aldren, Kaelor e Theron', 'Divisão das Doze Legiões e dos celeiros reais'],
    phases: ['Primeiro cisma das legiões', 'Campanhas dos três estandartes', 'Guerra de desgaste regional', 'Ascensão reunificadora de Marcellus Veyron'],
    consequences: ['Milhões de mortos ao longo de cerca de um século', 'Destruição da legitimidade da Coroa Una', 'Marcellus Veyron reúne os territórios exauridos'],
    category: 'Era histórica',
    status: 'Encerrada',
    period: 'Ano 0–100',
    events: ['Cisma das Doze Legiões', 'Cerco dos Três Estandartes', 'Tratado das Cinzas'],
    curiosities: ['O ano zero marca a morte de Edric, não a fundação do continente.', 'Quatro estradas reais atuais seguem rotas militares abertas durante a guerra.'],
    quotes: ['Toda coroa nasce de uma escolha — e toda escolha cobra sangue.'],
    relations: [{ label: 'Guerra dos Três Herdeiros', to: '/guerras/guerra-dos-tres-herdeiros' }],
  }),
  record({
    id: 'queda-coroa',
    name: 'II — A Queda da Coroa',
    subtitle: 'Reunificação, fome e regicídio',
    summary: 'Marcellus Veyron reunificou o reino pela força, mas sua tirania culminou na Noite das Doze Adagas e numa fragmentação definitiva.',
    description: 'Marcellus Veyron venceu o que restava das legiões e prometeu restaurar estradas e colheitas. A reconstrução veio acompanhada de tributos impossíveis, vigilância e confisco de sementes. Na capital, doze comandantes que sustentavam o regime o mataram na Noite das Doze Adagas. A morte do soberano soltou governadores militares e consolidou Winterfeld, Valoria, Ravenhold e Eldemar como estados humanos independentes.',
    causes: ['Centralização pela conquista', 'Tributos impossíveis', 'Fome, vigilância e confisco de sementes'],
    consequences: ['Morte de Veyron por doze comandantes', 'Formação política dos quatro reinos humanos', 'Desaparecimento das doze armas e disputa pela memória do regicídio'],
    category: 'Era histórica',
    status: 'Encerrada',
    period: 'Ano 101–158',
    events: ['Marcha de Veyron', 'Fome dos Sete Invernos', 'Noite das Doze Adagas'],
    curiosities: ['Nenhuma das doze adagas foi encontrada.', 'Valoria conserva os maiores arquivos fiscais do período.'],
    quotes: ['Os impérios raramente caem de fora. Primeiro apodrecem por dentro.'],
    relations: [{ label: 'Noite das Doze Adagas', to: '/lendas/noite-das-doze-adagas' }],
  }),
  record({
    id: 'era-magia',
    name: 'III — A Era da Magia',
    subtitle: 'O mundo antigo se deixa perceber',
    summary: 'Expedições registraram povos antigos, criaturas raras e as três linhagens hereditárias de bruxos: Kayler, Nimbus e Rivs.',
    description: 'A abertura de rotas além das antigas fronteiras humanas revelou que Avernor nunca estivera vazio. Elfos de Sylvaris, anões de Kar-Dûm e comunidades das terras selvagens já possuíam calendários e memórias próprias. Nesse período, as Casas Kayler, Nimbus e Rivs tornaram pública a existência da magia verdadeira — um dom de sangue que não pode ser ensinado a quem não nasceu nessas linhagens.',
    consequences: ['Primeiros tratados estáveis com povos antigos', 'Centralidade política de Kayler, Nimbus e Rivs', 'Formulação pública do Juramento Arcano'],
    category: 'Era histórica',
    status: 'Encerrada',
    period: 'Ano 159–310',
    events: ['Primeiro Concílio de Lethariel', 'Abertura dos Portões de Kar-Dûm', 'Registro das Três Linhagens'],
    curiosities: ['O termo “descoberta da magia” é rejeitado pelos cronistas élficos.', 'Os primeiros tratados confundiam feitiçaria hereditária com práticas religiosas.'],
    quotes: ['A magia não foi descoberta. Ela apenas permitiu que o mundo a percebesse.'],
    relations: [{ label: 'Casa Kayler', to: '/casas/kayler' }, { label: 'Casa Nimbus', to: '/casas/nimbus' }, { label: 'Casa Rivs', to: '/casas/rivs' }],
  }),
  record({
    id: 'era-coroas',
    name: 'IV — A Era das Coroas',
    subtitle: 'Alianças, fronteiras e o auge de Normus',
    summary: 'Reinos consolidaram suas identidades e disputaram a lealdade dos bruxos. Normus Kayler tornou-se a maior força arcana conhecida.',
    description: 'A estabilidade das novas coroas trouxe prosperidade desigual e a Guerra dos Tronos. Reis competiram pelo apoio das três Casas. Normus recusou servir a um soberano, defendeu Kar-Dûm e depois Sylvaris contra invasões orcs, recebendo o título de Cavaleiro de Honra — o único não elfo a conquistá-lo. Nesse período o dragão branco Vyrasul passou a ser associado a Winterfeld sem pertencer à coroa.',
    phases: ['Guerra dos Tronos', 'Defesa de Kar-Dûm', 'Invasões orcs contra Sylvaris', 'Nomeação de Normus como Cavaleiro de Honra'],
    consequences: ['Prestígio continental de Normus', 'Medo crescente das coroas diante dos bruxos', 'Associação cultural entre Vyrasul e Winterfeld'],
    category: 'Era histórica',
    status: 'Encerrada',
    period: 'Ano 311–612',
    events: ['Pacto das Sete Pontes', 'Defesa de Sylvaris', 'Juramento de Normus'],
    curiosities: ['O título de Normus não o colocou na linha sucessória élfica.', 'A amizade entre Normus e a Rainha de Sylvaris foi política e pessoal, jamais amorosa.'],
    quotes: ['Quando reis cobiçam a mesma força, a paz se torna apenas o intervalo entre duas batalhas.'],
    relations: [{ label: 'Normus Kayler', to: '/personagens/normus-kayler' }, { label: 'Rainha Aelwen', to: '/personagens/rainha-aelwen' }],
  }),
  record({
    id: 'caca-bruxas',
    name: 'V — A Caça às Bruxas',
    subtitle: 'O medo transforma protetores em presas',
    summary: 'Reis e inquisidores perseguiram Nimbus, Rivs e Kayler até quase apagarem as três linhagens. Sirius nasceu no fim dessa era.',
    description: 'Sete reis reunidos em conselho decidiram controlar ou eliminar as três Casas. Os Nimbus foram destruídos lutando; os Rivs esconderam bibliotecas e desapareceram. Normus firmou com a Rainha de Sylvaris um pacto de proteção aos descendentes, partiu, conheceu Namídia na fortaleza rebelde das Montanhas Cinzentas e viveu com ela perto da Floresta Antiga e do mar. Sirius nasceu ali. Namídia morreu protegendo o filho; Normus travou sua batalha final e os Kayler foram dados como extintos.',
    causes: ['Conselho dos Sete Reis', 'Medo de que um bruxo decidisse guerras', 'Planos de registro, controle e tomada de crianças'],
    phases: ['Resistência final dos Nimbus', 'Evacuação das bibliotecas Rivs', 'Pacto entre Normus e Sylvaris', 'Vida de Normus e Namídia junto à Floresta Antiga', 'Nascimento de Sirius e batalha final'],
    consequences: ['Nimbus considerados destruídos', 'Rivs desaparecidos com parte do conhecimento', 'Kayler considerados extintos', 'Sirius preservado como último bruxo conhecido'],
    category: 'Era histórica',
    status: 'Encerrada',
    period: 'Ano 613–704',
    events: ['Edito da Cinza Branca', 'Cerco da Fortaleza do Véu', 'Nascimento de Sirius Kayler'],
    curiosities: ['Muitos registros da perseguição foram deliberadamente alterados.', 'Sirius é considerado o último bruxo conhecido, não necessariamente o último sobrevivente possível.'],
    quotes: ['O mundo chamou de monstros aqueles que antes chamava de heróis.'],
    relations: [{ label: 'Guerra da Cinza Branca', to: '/guerras/guerra-da-cinza-branca' }, { label: 'Sirius Kayler', to: '/personagens/sirius-kayler' }, { label: 'Casa Kayler', to: '/casas/kayler' }, { label: 'Casa Nimbus', to: '/casas/nimbus' }, { label: 'Casa Rivs', to: '/casas/rivs' }],
  }),
]

export const eras = eraRecords.map((era) => ({ ...era, ...eraDossiers[era.id] }))
