import { record } from '../schema.js'

export const books = [
  record({ id: 'o-ultimo-bruxo', name: 'I — O Último Bruxo', subtitle: 'O legado desperta', summary: 'Sirius recebe os pertences de Normus e descobre que a paz de seu isolamento foi construída sobre um pacto incompleto.', description: 'O primeiro volume acompanha a saída de Sirius da Floresta Antiga, o encontro com Elara e a abertura da carta cifrada de Normus. O conflito central não é dominar um poder novo, mas decidir em quem confiar quando reinos tentam transformar sua existência em vantagem política.', category: 'Saga de Sirius Kayler', status: 'Em desenvolvimento', period: 'Era atual', relations: [{ label: 'Sirius Kayler', to: '/personagens/sirius-kayler' }, { label: 'Elara', to: '/personagens/elara' }], events: ['A entrega da herança', 'O salto de Elara', 'A estrada para Valoria'] }),
  record({ id: 'a-carta-e-a-tempestade', name: 'II — A Carta e a Tempestade', subtitle: 'Verdade em linguagem de cerco', summary: 'A cifra Bellatrix conduz Sirius e Elara às Montanhas Cinzentas enquanto Ravenhold fecha as passagens.', description: 'Fragmentos da carta revelam que a perseguição pode ter poupado membros das Casas Nimbus e Rivs. Para seguir a pista, o grupo precisa atravessar Valoria sem provocar intervenção real e alcançar a Fortaleza do Véu antes das primeiras neves.', category: 'Saga de Sirius Kayler', status: 'Planejado', period: 'Era atual', relations: [{ label: 'Namídia Bellatrix', to: '/personagens/namidia-bellatrix' }, { label: 'Fortaleza do Véu', to: '/cidades/fortaleza-do-veu' }] }),
  record({ id: 'cronicas-perdidas-de-sylvaris', name: 'Crônicas Perdidas de Sylvaris', subtitle: 'Registros da Caça às Bruxas', summary: 'Compilação clandestina de testemunhos preservados pelos Círculos da Memória.', description: 'O texto reúne listas de refugiados, decisões controversas da Rainha e relatos sobre a morte de Namídia. Nomes de sobreviventes permanecem ocultos. O exemplar público é uma edição comentada, não o arquivo integral.', category: 'Crônica histórica', status: 'Acesso parcial', origin: 'Sylvaris', period: 'Caça às Bruxas', relations: [{ label: 'Caça às Bruxas', to: '/historia/caca-bruxas' }] }),
  record({ id: 'atlas-das-sete-rotas', name: 'Atlas das Sete Rotas', subtitle: 'Estradas, rios e custos de travessia', summary: 'Manual de cartógrafos que descreve deslocamento, pedágios, estações e riscos entre os principais reinos.', description: 'Atualizado por viajantes credenciados, o atlas registra distâncias por tempo e carga, não apenas por léguas. Divergências entre edições ajudam historiadores a reconstruir guerras, pontes destruídas e mudanças de fronteira.', category: 'Atlas', status: 'Atualizado anualmente', origin: 'Eldemar e Valoria', relations: [{ label: 'Atlas de Avernor', to: '/atlas' }] }),
  record({ id: 'tratado-das-linhagens', name: 'Tratado das Linhagens', subtitle: 'O que a magia é — e o que não é', summary: 'Estudo que diferencia magia hereditária das três Casas, artefatos rúnicos e práticas religiosas.', description: 'A obra insiste que pessoas sem sangue Kayler, Nimbus ou Rivs não podem aprender magia verdadeira. Técnicas rúnicas dependem de objetos e conhecimento artesanal; ritos religiosos organizam comunidades, mas não concedem o dom hereditário.', category: 'Tratado arcano', status: 'Preservado com lacunas', origin: 'Arquivo Rivs', period: 'Era da Magia', relations: [{ label: 'Casa Kayler', to: '/casas/kayler' }, { label: 'Casa Nimbus', to: '/casas/nimbus' }, { label: 'Casa Rivs', to: '/casas/rivs' }] }),
  record({ id: 'caderno-de-namidia', name: 'Caderno de Namídia', subtitle: 'Inventários que escondem pessoas', summary: 'Livro de administração da Fortaleza do Véu cuja contabilidade contém cifras sobre rotas de fuga.', description: 'Linhas aparentemente dedicadas a grãos, óleo e sal escondem nomes e destinos. O caderno comprova que Namídia organizou uma rede maior do que as histórias heroicas sugerem: dezenas de pessoas comuns mantiveram postos, mulas e abrigos.', category: 'Documento pessoal', status: 'Em decifração', origin: 'Fortaleza do Véu', period: 'Caça às Bruxas', relations: [{ label: 'Namídia Bellatrix', to: '/personagens/namidia-bellatrix' }] }),
]
