import { record } from '../schema.js'
import { applyArchiveDossiers, bookArchiveDossiers } from '../editorial/archiveDossiers.js'

const bookRecords = [
  record({ id: 'o-ultimo-bruxo', name: 'I — O Último Bruxo', subtitle: 'O legado desperta', summary: 'Sirius recebe os pertences de Normus e descobre que a paz de seu isolamento foi construída sobre um pacto incompleto.', description: 'O primeiro volume acompanha a saída de Sirius da Floresta Antiga, o encontro com Elara e a abertura da carta cifrada de Normus. O conflito central não é dominar um poder novo, mas decidir em quem confiar quando reinos tentam transformar sua existência em vantagem política.', category: 'Saga de Sirius Kayler', status: 'Em desenvolvimento', period: 'Era atual', relations: [{ label: 'Sirius Kayler', to: '/personagens/sirius-kayler' }, { label: 'Elara', to: '/personagens/elara' }], events: ['A entrega da herança', 'O salto de Elara', 'A estrada para Valoria'] }),
  record({ id: 'a-carta-e-a-tempestade', name: 'II — A Carta e a Tempestade', subtitle: 'Verdade em linguagem de cerco', summary: 'A cifra Bellatrix conduz Sirius e Elara às Montanhas Cinzentas enquanto Ravenhold fecha as passagens.', description: 'Fragmentos da carta revelam que a perseguição pode ter poupado membros das Casas Nimbus e Rivs. Para seguir a pista, o grupo precisa atravessar Valoria sem provocar intervenção real e alcançar a Fortaleza do Véu antes das primeiras neves.', category: 'Saga de Sirius Kayler', status: 'Planejado', period: 'Era atual', relations: [{ label: 'Namídia Bellatrix', to: '/personagens/namidia-bellatrix' }, { label: 'Fortaleza do Véu', to: '/cidades/fortaleza-do-veu' }] }),
  record({ id: 'cronicas-perdidas-de-sylvaris', name: 'Crônicas Perdidas de Sylvaris', subtitle: 'Registros da Caça às Bruxas', summary: 'Compilação clandestina de testemunhos preservados pelos Círculos da Memória.', description: 'O texto reúne listas de refugiados, decisões controversas da Rainha e relatos sobre a morte de Namídia. Nomes de sobreviventes permanecem ocultos. O exemplar público é uma edição comentada, não o arquivo integral.', category: 'Crônica histórica', status: 'Acesso parcial', origin: 'Sylvaris', period: 'Caça às Bruxas', relations: [{ label: 'Caça às Bruxas', to: '/historia/caca-bruxas' }] }),
  record({ id: 'atlas-das-sete-rotas', name: 'Atlas das Sete Rotas', subtitle: 'Estradas, rios e custos de travessia', summary: 'Manual de cartógrafos que descreve deslocamento, pedágios, estações e riscos entre os principais reinos.', description: 'Atualizado por viajantes credenciados, o atlas registra distâncias por tempo e carga, não apenas por léguas. Divergências entre edições ajudam historiadores a reconstruir guerras, pontes destruídas e mudanças de fronteira.', category: 'Atlas', status: 'Atualizado anualmente', origin: 'Eldemar e Valoria', relations: [{ label: 'Atlas de Avernor', to: '/atlas' }] }),
  record({ id: 'tratado-das-linhagens', name: 'Tratado das Linhagens', subtitle: 'O que a magia é — e o que não é', summary: 'Estudo que diferencia magia hereditária das três Casas, artefatos rúnicos e práticas religiosas.', description: 'A obra insiste que pessoas sem sangue Kayler, Nimbus ou Rivs não podem aprender magia verdadeira. Técnicas rúnicas dependem de objetos e conhecimento artesanal; ritos religiosos organizam comunidades, mas não concedem o dom hereditário.', category: 'Tratado arcano', status: 'Preservado com lacunas', origin: 'Arquivo Rivs', period: 'Era da Magia', relations: [{ label: 'Casa Kayler', to: '/casas/kayler' }, { label: 'Casa Nimbus', to: '/casas/nimbus' }, { label: 'Casa Rivs', to: '/casas/rivs' }] }),
  record({ id: 'caderno-de-namidia', name: 'Caderno de Namídia', subtitle: 'Inventários que escondem pessoas', summary: 'Livro de administração da Fortaleza do Véu cuja contabilidade contém cifras sobre rotas de fuga.', description: 'Linhas aparentemente dedicadas a grãos, óleo e sal escondem nomes e destinos. O caderno comprova que Namídia organizou uma rede maior do que as histórias heroicas sugerem: dezenas de pessoas comuns mantiveram postos, mulas e abrigos.', category: 'Documento pessoal', status: 'Em decifração', origin: 'Fortaleza do Véu', period: 'Caça às Bruxas', relations: [{ label: 'Namídia Bellatrix', to: '/personagens/namidia-bellatrix' }] }),
  record({
    id: 'livro-dos-caminhos-fechados',
    name: 'Livro dos Caminhos Fechados',
    subtitle: 'Por que uma estrada deixou de existir',
    summary: 'Registro de Sylvaris que documenta rotas recolhidas, seus motivos e as condições necessárias para uma possível reabertura.',
    description: 'O Livro dos Caminhos Fechados não é um mapa secreto nem um catálogo de atalhos. Cada verbete público descreve uma passagem que deixou de ser mantida por erosão, luto, risco ecológico, guerra ou pedido das comunidades ligadas a ela. Coordenadas utilizáveis são removidas das cópias abertas; permanecem o motivo, a autoridade responsável e a data de revisão. A prática impede que uma trilha desapareça da memória apenas porque sumiu do terreno, mas também evita que curiosidade histórica exponha refúgios e áreas de recuperação. Algumas folhas anteriores à Caça às Bruxas estão perdidas, e cópias humanas frequentemente inventam destinos para preencher as lacunas.',
    category: 'Registro territorial',
    status: 'Edição pública com coordenadas omitidas',
    truthStatus: 'redacted',
    knowledgeStatus: 'people-only',
    confidence: 'high',
    origin: 'Círculos da Memória de Sylvaris',
    period: 'Compilação contínua',
    archivalOverview: 'O códice preserva razões e responsabilidades associadas a rotas encerradas sem publicar caminhos capazes de ameaçar comunidades.',
    provenance: 'Colofões sazonais, atas dos Círculos e marcas botânicas permitem distinguir revisões autênticas de cópias de viajantes.',
    publicKnowledge: ['Toda rota recolhida deve ter uma justificativa, um responsável e uma data de reavaliação.'],
    knowledgeGaps: ['Coordenadas de refúgio, nomes protegidos e folhas destruídas durante a perseguição não integram a edição pública.'],
    culturalReadings: ['Sylvaris o lê como compromisso com território e memória; mercadores estrangeiros o acusam de ocultar vantagens comerciais.'],
    historicalSources: ['Edição pública comentada', 'Atas sazonais dos Círculos', 'Catálogo de folhas perdidas'],
    disputedClaims: ['Cópias que prometem uma estrada direta até Lethariel não possuem proveniência autenticada.'],
    narrativeImportance: 'Dá contexto às mudanças de rota da Floresta Antiga e sustenta investigações sem revelar automaticamente caminhos ainda sensíveis.',
    imageBrief: 'Códice élfico verde-escuro aberto sobre mesa de madeira caída, diagramas de pontes recolhidas sem mapa legível nem texto gerado.',
    sections: [
      { title: 'Critério de fechamento', body: 'A interrupção precisa registrar dano possível, consulta às comunidades e quem responderá pela revisão futura.' },
      { title: 'Edição pública', body: 'Leitores recebem contexto histórico e ecológico, mas não direções capazes de reabrir a passagem por conta própria.' },
      { title: 'Folhas perdidas', body: 'Incêndios, fuga e remoção deliberada deixaram lacunas que permanecem declaradas, nunca preenchidas como certeza.' },
      { title: 'Uso contemporâneo', body: 'Elara e os guardiões consultam o livro quando rotas antigas reaparecem em cartas ligadas à perseguição.' },
    ],
    relations: [
      { label: 'Sylvaris', to: '/reinos/sylvaris' },
      { label: 'Floresta Antiga', to: '/locais/floresta-antiga' },
      { label: 'Jardim das Pontes Silenciosas', to: '/locais/jardim-das-pontes-silenciosas' },
      { label: 'Elara', to: '/personagens/elara' },
    ],
  }),
  record({
    id: 'registro-das-aguas-partilhadas',
    name: 'Registro das Águas Partilhadas',
    subtitle: 'Tratados que começam no poço',
    summary: 'Coleção multilíngue de acordos sobre poços, canais e travessias entre Valoria, cidades de Zharak e clãs de Vul’Gar.',
    description: 'O Registro das Águas Partilhadas reúne cópias de tratados que não pertencem a uma única coroa. Cada acordo aparece nos idiomas dos signatários, acompanhado por medidas de vazão, períodos de seca e obrigações de reparo. A coleção demonstra que comunidades consideradas rivais suspenderam hostilidades perto de poços muito antes de diplomatas transformarem a prática em lei escrita. Nem todos os pactos continuam vigentes: canais mudaram, assentamentos desapareceram e alguns selos são contestados. A edição pública identifica essas diferenças e se recusa a apresentar costume vivo como concessão histórica de Valoria.',
    category: 'Coleção de tratados',
    status: 'Vigência variável por documento',
    truthStatus: 'documented',
    knowledgeStatus: 'documented',
    confidence: 'high',
    origin: 'Copistas de Valoria, Zharak e Vul’Gar',
    period: 'Documentos de diferentes eras',
    archivalOverview: 'A coleção preserva pactos de água como acordos multilaterais e materiais, não como prova de soberania de um povo sobre outro.',
    provenance: 'Selos, traduções paralelas, marcas de vazão e testemunhos comunitários permitem verificar a maioria dos documentos.',
    publicKnowledge: ['Poços de trégua e reparos compartilhados antecedem várias fronteiras políticas atuais.'],
    knowledgeGaps: ['Três pactos citam assentamentos não localizados e dois anexos de rota foram perdidos.'],
    culturalReadings: ['Valoria enfatiza a força contratual; comunidades de Zharak e Vul’Gar destacam que o costume existia antes da escrita cortesã.'],
    historicalSources: ['Placas de poço', 'Cópias das Sete Pontes', 'Memórias orais verificadas pelos clãs'],
    disputedClaims: ['Um selo Arden em cópia tardia não prova que a Casa tenha criado ou governado a trégua original.'],
    narrativeImportance: 'Oferece base histórica para evitar guerra por água e evidencia falsificações usadas para justificar pedágios ou ocupação.',
    imageBrief: 'Três conjuntos de documentos, placas de argila e tigela de água sobre mesa diplomática, selos diferentes e nenhuma escrita legível.',
    sections: [
      { title: 'A trégua do poço', body: 'A regra suspende violência no círculo de acesso e obriga todos os presentes a impedir contaminação.' },
      { title: 'Medidas incompatíveis', body: 'Copistas registram equivalências entre calendários, vazões e unidades para impedir vantagem por tradução.' },
      { title: 'Pactos contestados', body: 'Documentos sem comunidade viva ou sem fonte de água localizável permanecem históricos, não automaticamente vigentes.' },
      { title: 'Uso na crise atual', body: 'Mercadores e emissários consultam a coleção quando secas reduzem poços orientais e elevam a tensão com Ravenhold.' },
    ],
    relations: [
      { label: 'Valoria', to: '/reinos/valoria' },
      { label: 'Deserto de Zharak', to: '/locais/deserto-de-zharak' },
      { label: 'Orcs', to: '/povos/orcs' },
      { label: 'Mercado dos Três Ventos', to: '/locais/mercado-dos-tres-ventos' },
    ],
  }),
  record({
    id: 'codice-dos-estandartes-baixos',
    name: 'Códice dos Estandartes Baixos',
    subtitle: 'Ordens recusadas, civis protegidos e comando sob revisão',
    summary: 'Compilação de Ravenhold dedicada a decisões militares interrompidas por oficiais, soldados e comunidades durante a perseguição.',
    description: 'O Códice dos Estandartes Baixos foi organizado depois que a Caça às Bruxas revelou a insuficiência de registrar apenas ordens cumpridas. Suas páginas reúnem cópias de comandos recusados, justificativas apresentadas em conselho, punições posteriores e testemunhos de civis que sobreviveram graças à demora ou à desobediência. O título vem do gesto de baixar o estandarte de uma unidade quando sua autoridade é suspensa para investigação. A obra não transforma toda recusa em heroísmo: algumas esconderam deserção, pilhagem ou rivalidade. Nomes de testemunhas vulneráveis são omitidos da edição pública, e anexos de responsabilidade ainda passam por auditoria.',
    category: 'Crônica militar e cívica',
    status: 'Edição pública revisada',
    truthStatus: 'documented',
    knowledgeStatus: 'documented',
    confidence: 'high',
    origin: 'Arquivo das Ordens de Ravencastle',
    period: 'Compilado após a Caça às Bruxas',
    archivalOverview: 'O códice documenta consciência, responsabilidade e consequência dentro de uma cultura militar sem absolver o aparato de perseguição.',
    provenance: 'Ordens numeradas, registros de guarnição e depoimentos civis convergem em parte substancial dos casos publicados.',
    publicKnowledge: ['Ravenhold preserva ordens recusadas e distingue suspensão legal, desobediência responsável e abandono criminoso.'],
    knowledgeGaps: ['Anexos selados, nomes protegidos e cadeias de comando incompletas impedem atribuição definitiva em alguns episódios.'],
    culturalReadings: ['Reformistas o tratam como base de direito cívico; tradicionalistas afirmam que ele enfraquece comando em fronteira.'],
    historicalSources: ['Arquivo das Ordens', 'Atas do Senado de Estandartes', 'Depoimentos de bairros de Ravencastle'],
    disputedClaims: ['Listas tardias que atribuem toda recusa a uma única facção não coincidem com os livros de guarnição.'],
    narrativeImportance: 'Coloca a disputa sucessória de Ravenhold diante de provas históricas e oferece ferramentas para avaliar ordens atuais de bandeira falsa.',
    imageBrief: 'Códice militar de couro escuro, estandarte dobrado, selo senatorial e folhas de ordens sobre mesa austera, sem texto legível.',
    sections: [
      { title: 'Por que o arquivo mudou', body: 'A perseguição mostrou que registrar somente execução tornava invisíveis escolhas, recusas e alternativas disponíveis.' },
      { title: 'Casos preservados', body: 'Cada entrada separa ordem, contexto, resposta, consequência disciplinar e testemunho civil quando existe.' },
      { title: 'Nomes protegidos', body: 'A edição pública omite pessoas que poderiam sofrer represália sem apagar seu papel histórico.' },
      { title: 'Debate no presente', body: 'A sucessão Corven e ataques de fronteira renovaram a disputa sobre quando consciência integra o juramento militar.' },
    ],
    relations: [
      { label: 'Ravenhold', to: '/reinos/ravenhold' },
      { label: 'Ravencastle', to: '/cidades/ravencastle' },
      { label: 'Torre da Chuva Negra', to: '/locais/torre-da-chuva-negra' },
      { label: 'Caça às Bruxas', to: '/historia/caca-bruxas' },
    ],
  }),
]

export const books = applyArchiveDossiers(bookRecords, bookArchiveDossiers)
