import { record } from '../schema.js'
import { religionDossiers } from '../beliefs/dossiers.js'

const religionRecords = [
  record({ id: 'caminho-das-raizes', name: 'Caminho das Raízes', subtitle: 'Memória, reciprocidade e floresta', summary: 'Tradição de Sylvaris que entende os vivos como hóspedes temporários de uma memória ecológica maior.', description: 'Não há divindade central. Ritos registram nascimentos, mortes e mudanças no território. Decisões religiosas têm consequência prática: áreas de luto ficam sem colheita por uma estação para permitir recuperação do solo.', category: 'Tradição élfica', status: 'Praticada', origin: 'Sylvaris', location: 'Floresta Antiga', relations: [{ label: 'Sylvaris', to: '/reinos/sylvaris' }] }),
  record({ id: 'culto-da-brasa-comum', name: 'Culto da Brasa Comum', subtitle: 'Nenhum fogo pertence a uma só casa', summary: 'Prática comunitária humana centrada na manutenção de fogos públicos durante inverno, fome e guerra.', description: 'Templos funcionam como cozinhas, abrigos e depósitos. Sacerdotes são avaliados pela administração das reservas, não por milagres. O culto cresceu após a Fome dos Sete Invernos e frequentemente entra em conflito com nobres que desejam controlar doações.', category: 'Religião comunitária', status: 'Praticada', origin: 'Valoria', location: 'Reinos humanos' }),
  record({ id: 'nove-ecos', name: 'Os Nove Ecos', subtitle: 'A pedra devolve o que fazemos', summary: 'Filosofia anã segundo a qual toda obra produz consequências que retornam por caminhos materiais e sociais.', description: 'Cada eco representa uma responsabilidade: água, ar, estrutura, calor, trabalho, memória, troca, abrigo e reparo. Antes de uma grande escavação, nove especialistas respondem publicamente por esses efeitos.', category: 'Filosofia anã', status: 'Praticada', origin: 'Kar-Dûm', location: 'Salões anões', relations: [{ label: 'Kar-Dûm', to: '/reinos/kar-dum' }] }),
  record({ id: 'juramento-do-horizonte', name: 'Juramento do Horizonte', subtitle: 'A fé dos que partem e retornam', summary: 'Tradição marítima de Eldemar baseada em promessas registradas antes de cada viagem.', description: 'Tripulações escrevem obrigações com famílias e companheiros em placas de cera. Ao retornar, devem cumprir ou explicar cada promessa diante do cais. O rito reduz abandono de dependentes e funciona como contrato comunitário.', category: 'Tradição marítima', status: 'Praticada', origin: 'Eldemar', location: 'Portos de Avernor', relations: [{ label: 'Eldemar', to: '/reinos/eldemar' }] }),
  record({ id: 'fe-dos-sete-nomes', name: 'Fé dos Sete Nomes', subtitle: 'Sete virtudes, muitas instituições', summary: 'Família de religiões humanas que nomeia justiça, coragem, sabedoria, compaixão, memória, mudança e morte.', description: 'Os nomes são Avar, coragem que permanece; Edria, justiça sem proprietário; Saelor, sabedoria que pergunta; Miren, compaixão que abriga; Veyra, memória que testemunha; Ordan, mudança que abre caminho; e Namar, morte que encerra dívidas. Nenhuma vertente concede magia. Reis usam os nomes para legitimar-se, enquanto reformistas recordam que virtudes não pertencem a coroas.', category: 'Religião humana', status: 'Amplamente praticada', origin: 'Reino humano antigo', location: 'Reinos humanos', truthStatus: 'documented', beliefs: ['Virtudes não são propriedade de governantes', 'Mortos são confiados a Namar e lembrados por Veyra', 'Avar não justifica guerra sem responsabilidade'], relations: [{ label: 'Humanos de Avernor', to: '/povos/humanos' }] }),
  record({ id: 'coroa-dourada', name: 'Culto da Coroa Dourada', subtitle: 'A vertente valoriana dos Sete Nomes', summary: 'Tradição que mede justiça pela capacidade de manter colheitas, pesos e pactos públicos.', description: 'Templos funcionam como tribunais de medida e celeiros de emergência. A ala cortesã afirma que a coroa representa Edria; a ala do Campo Aberto responde que nenhuma pessoa pode encarnar uma virtude. A disputa alimenta reformas agrárias sem transformar fé em feitiço.', category: 'Vertente humana', status: 'Dividida', origin: 'Valoria', location: 'Valoria', truthStatus: 'documented', relations: [{ label: 'Valoria', to: '/reinos/valoria' }, { label: 'Casa Arden', to: '/casas/arden' }] }),
  record({ id: 'vigilia-ultima-brasa', name: 'Vigília da Última Brasa', subtitle: 'A fé do abrigo setentrional', summary: 'Vertente de Winterfeld que mantém um fogo público até a última pessoa encontrar abrigo.', description: 'Durante as quarenta noites de portões fechados, vigias registram estoque e presença. Fanáticos já tentaram declarar o dragão Vyrasul emissário divino; o concílio local rejeita a tese e o trata como criatura natural. Abandonar alguém ao frio é a principal ruptura moral.', category: 'Vertente humana', status: 'Praticada', origin: 'Winterfeld', location: 'Winterfeld', truthStatus: 'documented', relations: [{ label: 'Winterfeld', to: '/reinos/winterfeld' }, { label: 'Vyrasul', to: '/criaturas/vyrasul' }] }),
  record({ id: 'vigilia-sol-negro', name: 'Vigília do Sol Negro', subtitle: 'Memória e disciplina em Ravenhold', summary: 'Religião de veteranos que registra ordens recusadas, obedecidas e lamentadas.', description: 'O disco negro representa o momento em que obediência encobre consciência. Uma ala militar justificou a Caça às Bruxas; penitentes atuais preservam listas de vítimas e defendem direito formal à recusa. O conflito religioso atravessa o Senado de Estandartes.', category: 'Vertente humana', status: 'Em reforma', origin: 'Ravenhold', location: 'Ravenhold', truthStatus: 'documented', relations: [{ label: 'Ravenhold', to: '/reinos/ravenhold' }, { label: 'Caça às Bruxas', to: '/historia/caca-bruxas' }] }),
  record({ id: 'chama-sem-coroa', name: 'A Chama sem Coroa', subtitle: 'Nenhum governante é sagrado', summary: 'Crença rebelde das Montanhas Cinzentas que coloca juramento ao povo acima de juramento ao trono.', description: 'Seu símbolo é uma chama dentro de uma coroa quebrada. Mortos são lembrados por atos, liberdade deve ser defendida e proteger perseguidos pode ser dever sagrado. Namídia Bellatrix renovou o rito ao abrir a Fortaleza do Véu a fugitivos, sem possuir magia ou autoridade divina.', category: 'Crença rebelde', status: 'Praticada', origin: 'Montanhas Cinzentas', location: 'Fortalezas rebeldes', truthStatus: 'documented', beliefs: ['Nenhum governante é sagrado', 'Juramento ao povo supera juramento ao trono', 'Abrigar perseguidos pode ser dever sagrado'], relations: [{ label: 'Namídia Bellatrix', to: '/personagens/namidia-bellatrix' }, { label: 'Fortaleza do Véu', to: '/cidades/fortaleza-do-veu' }] }),
]

export const religions = religionRecords.map((religion) => ({ ...religion, ...religionDossiers[religion.id] }))
