import { record } from '../schema.js'

const regionalContext = {
  winterfeld: { kingdom: 'Winterfeld', location: 'Norte glacial', climate: 'Glacial, com neve persistente e degelos breves.' },
  montanhas: { kingdom: 'Montanhas Cinzentas', location: 'Cordilheira setentrional', climate: 'Frio e seco, com ventos de altitude e vales de pouca luz.' },
  nevoeiro: { kingdom: 'Sem soberania única', location: 'Extremo nordeste marítimo', climate: 'Marítimo frio, encoberto por bancos de neblina.' },
  sylvaris: { kingdom: 'Sylvaris', location: 'Floresta Antiga', climate: 'Úmido e temperado sob a copa.' },
  valoria: { kingdom: 'Valoria', location: 'Planícies centrais', climate: 'Temperado, com cheias e verões de colheita.' },
  ravenhold: { kingdom: 'Ravenhold', location: 'Fronteira oriental', climate: 'Continental, seco e sujeito a grande variação sazonal.' },
  sombras: { kingdom: 'Controle interdito', location: 'Terras Sombrias', climate: 'Seco, com poeira metálica e água de qualidade incerta.' },
  'kar-dum': { kingdom: 'Kar-Dûm', location: 'Cordilheira central', climate: 'Subterrâneo estável, com extremos próximos às forjas.' },
  brumas: { kingdom: 'Sem soberania única', location: 'Arquipélago das Brumas', climate: 'Marítimo, úmido e sujeito a neblina.' },
  'vul-gar': { kingdom: 'Vul’Gar', location: 'Planaltos orientais', climate: 'Seco e quente, com estações de pouca água.' },
  zharak: { kingdom: 'Sem soberania única', location: 'Deserto de Zharak', climate: 'Árido, com forte amplitude térmica.' },
}

function mappedLocation({ region, id, name, category, summary, description, geography, status = 'Condição atual não registrada', truthStatus = 'witnessed' }) {
  const context = regionalContext[region]
  return record({
    id, name, category, summary, description, geography,
    subtitle: 'Topônimo preservado na carta oficial',
    status,
    kingdom: context.kingdom,
    location: context.location,
    climate: context.climate,
    currentSituation: 'A existência e a posição regional são testemunhadas pelo raster oficial; ocupação, governo local e condição em 1204 d.C. não foram registrados em fonte textual independente.',
    rumors: ['Não há rumor autenticado anexado a este verbete; versões orais permanecem não registradas.'],
    narrativeImportance: `O topônimo amplia a malha pública do Atlas e permite relacionar viagens e acontecimentos futuros a ${name} sem antecipar fatos ainda desconhecidos.`,
    knowledgeStatus: 'unrecorded',
    confidence: 'Alta para o topônimo e a posição regional; baixa para detalhes não desenhados.',
    sourceType: 'Testemunho cartográfico',
    sourceReliability: 'Carta oficial preservada; leitura aproximada de símbolo, relevo e rótulo.',
    sourceStatus: 'Baseado no raster oficial do Atlas',
    truthStatus,
    updatedAt: '2026-08-12',
    relations: [{ label: 'Localizar no Atlas', to: `/atlas?ponto=${id}` }],
  })
}

export const cartographicLocations = [
  mappedLocation({ region: 'winterfeld', id: 'fortaleza-gelida', name: 'Fortaleza Gélida', category: 'Fortaleza', summary: 'Reduto fortificado assinalado no extremo norte de Winterfeld, acima das rotas habitadas da coroa.', description: 'A carta mostra uma fortificação isolada entre gelo e relevo elevado, distante dos núcleos urbanos conhecidos. Seu fundador, sua guarnição e o vínculo administrativo com Winterheim não foram registrados; apenas nome, natureza defensiva e posição setentrional são testemunhados.', geography: 'Esporão rochoso cercado por gelo e acessos estreitos, conforme a leitura do símbolo cartográfico.', relation: { label: 'Winterfeld', to: '/reinos/winterfeld' } }),
  mappedLocation({ region: 'winterfeld', id: 'passagem-da-geada', name: 'Passagem da Geada', category: 'Passagem', summary: 'Corredor de altitude marcado entre os campos de gelo e as montanhas do norte.', description: 'O topônimo acompanha uma abertura estreita no relevo gelado, indicando passagem possível sem estabelecer estrada permanente. A duração do trânsito, os meses de abertura e eventuais pedágios são desconhecidos; a carta apenas confirma que cartógrafos distinguiam este corredor das geleiras vizinhas.', geography: 'Passo montanhoso sujeito a neve, gelo e fechamento sazonal não documentado.', relation: { label: 'Winterfeld', to: '/reinos/winterfeld' } }),
  mappedLocation({ region: 'montanhas', id: 'acampamento-da-liberdade', name: 'Acampamento da Liberdade', category: 'Acampamento', summary: 'Acampamento nomeado nas Montanhas Cinzentas, próximo às rotas de vigia do maciço.', description: 'Barracas e paliçadas aparecem na carta em uma clareira de altitude. O nome sugere uma memória política, mas atribuir fundadores, refugiados ou batalha seria especulação: autoria, população e duração do assentamento permanecem não registradas em fontes públicas.', geography: 'Clareira alta cercada por encostas rochosas e acessos que convergem para o acampamento.', relation: { label: 'Montanhas Cinzentas', to: '/reinos/montanhas-cinzentas' } }),
  mappedLocation({ region: 'montanhas', id: 'pico-da-vigia', name: 'Pico da Vigia', category: 'Pico', summary: 'Cume destacado no setor oriental das Montanhas Cinzentas.', description: 'O desenho do Atlas associa o nome a um pico dominante sobre vales e passagens próximas. A função de observação é uma leitura do topônimo, não prova de torre ou guarnição atual; acesso, altitude e ocupantes são desconhecidos.', geography: 'Pico de grande visibilidade regional, com encostas abruptas representadas na carta.', relation: { label: 'Montanhas Cinzentas', to: '/reinos/montanhas-cinzentas' } }),
  mappedLocation({ region: 'montanhas', id: 'fortaleza-esquecida', name: 'A Fortaleza Esquecida', category: 'Ruína fortificada', summary: 'Fortificação remota assinalada a leste da cordilheira, fora dos redutos de governo conhecido.', description: 'O Atlas preserva um nome que já expressa perda documental. Não há registro público de construtores, queda ou habitantes; mesmo sua condição de ruína é inferida pelo isolamento do símbolo e deve permanecer contestada até nova fonte.', geography: 'Fortificação sobre relevo elevado no limite nordeste conhecido da cordilheira.', relation: { label: 'Montanhas Cinzentas', to: '/reinos/montanhas-cinzentas' }, truthStatus: 'disputed' }),
  mappedLocation({ region: 'nevoeiro', id: 'ilhas-do-nevoeiro', name: 'Ilhas do Nevoeiro', category: 'Arquipélago', summary: 'Grupo insular desenhado no extremo nordeste do mapa, separado das coroas continentais.', description: 'A carta distingue várias ilhas entre bancos de névoa e mar aberto. Nenhum porto, povo soberano ou rota segura está confirmado no acervo textual; o registro reconhece somente o arquipélago e sua posição relativa.', geography: 'Ilhas rochosas dispersas em águas frias e frequentemente encobertas.', relation: { label: 'Atlas oficial', to: '/atlas' } }),
  mappedLocation({ region: 'valoria', id: 'campo-belo', name: 'Campo Belo', category: 'Povoado rural', summary: 'Assentamento das planícies de Valoria representado entre áreas agrícolas e travessias fluviais.', description: 'O símbolo da carta situa Campo Belo em terreno aberto ligado ao corredor de Valória. Produção, população e família governante não foram registradas; sua leitura como povoado agrário decorre apenas da posição entre campos desenhados.', geography: 'Planície cultivável próxima a cursos d’água e caminhos de travessia.', relation: { label: 'Valoria', to: '/reinos/valoria' } }),
  mappedLocation({ region: 'valoria', id: 'ponte-dourada', name: 'Ponte Dourada', category: 'Ponte', summary: 'Travessia nomeada no eixo oriental das planícies valorianas.', description: 'O Atlas marca uma ponte sobre curso d’água a leste do núcleo agrário. O material, a origem do nome e a autoridade que cobra passagem são desconhecidos; não deve ser confundida com as Sete Pontes de Valóris sem documento que prove essa relação.', geography: 'Travessia fluvial em corredor de planície, com acessos pelas duas margens.', relation: { label: 'Valoria', to: '/reinos/valoria' } }),
  mappedLocation({ region: 'ravenhold', id: 'muralha-de-pedra', name: 'Muralha de Pedra', category: 'Muralha', summary: 'Obra defensiva linear assinalada na fronteira de Ravenhold.', description: 'O traço fortificado da carta acompanha o limite ocidental de um corredor militar. Extensão, construtores e estado de conservação não estão documentados; o verbete evita transformá-la em fronteira política absoluta.', geography: 'Linha defensiva sobre planalto, vinculada a estradas e terrenos abertos.', relation: { label: 'Ravenhold', to: '/reinos/ravenhold' } }),
  mappedLocation({ region: 'ravenhold', id: 'campo-de-treinamento', name: 'Campo de Treinamento', category: 'Instalação militar', summary: 'Área militar nomeada nas proximidades das fortalezas centrais de Ravenhold.', description: 'A carta registra um campo aberto com função de treino, mas não informa qual legião, casa ou contingente o utiliza em 1204 d.C. Exercícios, capacidade e regras de acesso permanecem não registrados.', geography: 'Terreno nivelado de planalto, ligado por estrada a núcleos fortificados.', relation: { label: 'Ravenhold', to: '/reinos/ravenhold' } }),
  mappedLocation({ region: 'ravenhold', id: 'rio-torrente', name: 'Rio Torrente', category: 'Rio', summary: 'Curso d’água nomeado que atravessa a faixa meridional de Ravenhold.', description: 'O rio aparece como corredor natural entre planaltos e zonas fortificadas. Nascente, vazão sazonal e navegabilidade não possuem medição pública; qualquer uso militar ou comercial além do desenho cartográfico é desconhecido.', geography: 'Rio de planalto com direção regional indicada pelo raster, sem hidrografia detalhada.', relation: { label: 'Ravenhold', to: '/reinos/ravenhold' } }),
  mappedLocation({ region: 'ravenhold', id: 'fortaleza-solar', name: 'Fortaleza Solar', category: 'Fortaleza', summary: 'Fortaleza assinalada ao sul dos anéis centrais de Ravenhold.', description: 'O símbolo mostra uma obra defensiva conectada à malha oriental, mas nenhuma fonte pública identifica comandante, casa guardiã ou origem do epíteto Solar. Sua condição atual deve ser tratada como não registrada.', geography: 'Elevação fortificada próxima a estrada e ao sistema de rios do planalto.', relation: { label: 'Ravenhold', to: '/reinos/ravenhold' } }),
  mappedLocation({ region: 'sombras', id: 'necropole-de-valthor', name: 'Necrópole de Valthor', category: 'Necrópole', summary: 'Complexo funerário nomeado nas Terras Sombrias, a leste das rotas vigiadas.', description: 'O Atlas confirma o topônimo e um conjunto de estruturas em área interditada. Quem foi sepultado, quando o lugar recebeu o nome e se Valthor designa pessoa, povo ou cidade perdida são questões não registradas; relatos de atividade sobrenatural permanecem rumor.', geography: 'Ruínas funerárias em terreno seco, próximas a estradas abandonadas e zonas contaminadas.', relation: { label: 'Terras Sombrias', to: '/locais/terras-sombrias' }, status: 'Acesso interdito' }),
  mappedLocation({ region: 'sylvaris', id: 'clarifonte', name: 'Clarifonte', category: 'Assentamento', summary: 'Assentamento florestal desenhado junto a uma fonte ou curso d’água de Sylvaris.', description: 'A carta preserva Clarifonte entre árvores e água, sem distinguir vila, santuário ou posto de margem. População, círculo responsável e acesso para estrangeiros não estão registrados; a associação hídrica decorre apenas do nome e do desenho.', geography: 'Clareira arborizada junto a água corrente no interior de Sylvaris.', relation: { label: 'Sylvaris', to: '/reinos/sylvaris' } }),
  mappedLocation({ region: 'sylvaris', id: 'enaril', name: 'Enaril', category: 'Assentamento', summary: 'Núcleo nomeado no setor central da Floresta Antiga.', description: 'Enaril aparece como ponto habitado entre trilhas e copas densas. Não há fonte pública que esclareça governo, idade ou função ritual; sua existência cartográfica não autoriza tratar o local como cidade aberta.', geography: 'Assentamento sob copa fechada, conectado a trilhas internas não publicadas.', relation: { label: 'Sylvaris', to: '/reinos/sylvaris' } }),
  mappedLocation({ region: 'sylvaris', id: 'narin-falas', name: 'Narin’falas', category: 'Assentamento', summary: 'Topônimo élfico preservado no sul da Floresta Antiga.', description: 'O Atlas situa Narin’falas em área arborizada próxima aos caminhos meridionais. Tradução, população e relação com os Círculos da Memória permanecem conhecidas apenas pelos povos locais ou não registradas no arquivo comum.', geography: 'Bosque meridional de Sylvaris, entre elevações suaves e trilhas sazonais.', relation: { label: 'Sylvaris', to: '/reinos/sylvaris' } }),
  mappedLocation({ region: 'sylvaris', id: 'vale-das-estrelas', name: 'Vale das Estrelas', category: 'Vale', summary: 'Vale nomeado na borda sudoeste da Floresta Antiga.', description: 'O nome aparece sobre uma depressão aberta entre bosques. Não existe registro público de observatório, culto ou acontecimento celeste associado; tais leituras devem permanecer rumor até testemunho adicional.', geography: 'Vale de clareiras amplas cercado por mata e colinas baixas.', relation: { label: 'Sylvaris', to: '/reinos/sylvaris' } }),
  mappedLocation({ region: 'kar-dum', id: 'portao-de-karak', name: 'Portão de Karak', category: 'Portão fortificado', summary: 'Entrada monumental assinalada na face ocidental das montanhas de Kar-Dûm.', description: 'A carta reconhece um portão de superfície, mas não revela as galerias que ele protege. Guarnição, juramentos de entrada e significado de Karak são conhecidos apenas pelos registros anões ou permanecem não publicados.', geography: 'Portal escavado em encosta rochosa com acesso a redes subterrâneas não cartografadas.', relation: { label: 'Kar-Dûm', to: '/reinos/kar-dum' } }),
  mappedLocation({ region: 'kar-dum', id: 'salao-dos-forgemantes', name: 'Salão dos Forgemantes', category: 'Salão subterrâneo', summary: 'Salão de ofício nomeado na carta de Kar-Dûm, próximo às rotas centrais de forja.', description: 'A grafia do topônimo foi transcrita do raster e pode refletir tradição local ou erro de copista. Função, linhagens de ofício e acesso atual não foram confirmados por fonte textual; o registro conserva a forma cartográfica sem corrigi-la por conjectura.', geography: 'Complexo subterrâneo ligado a galerias de forja e ventilação.', relation: { label: 'Kar-Dûm', to: '/reinos/kar-dum' }, truthStatus: 'disputed' }),
  mappedLocation({ region: 'kar-dum', id: 'minas-de-ferro', name: 'Minas de Ferro', category: 'Minas', summary: 'Distrito de extração indicado no setor meridional de Kar-Dûm.', description: 'O símbolo cartográfico identifica minas de ferro sem informar veios ativos, salão proprietário ou volume de produção. Galerias internas não aparecem no mapa público, e sua condição de segurança é desconhecida.', geography: 'Encostas e galerias subterrâneas em zona mineral da cordilheira central.', relation: { label: 'Kar-Dûm', to: '/reinos/kar-dum' } }),
  mappedLocation({ region: 'brumas', id: 'ancoradouro-dos-piratas', name: 'Ancoradouro dos Piratas', category: 'Ancoradouro', summary: 'Enseada nomeada entre as ilhas ocidentais do Arquipélago das Brumas.', description: 'A carta assinala um abrigo marítimo ligado a piratas, mas não identifica frota, capitão ou permanência de ocupação. A designação pode ser advertência de navegadores e não reconhecimento de autoridade local.', geography: 'Enseada protegida por ilhas, recifes e canais rasos dependentes de piloto.', relation: { label: 'Arquipélago das Brumas', to: '/locais/arquipelago-das-brumas' } }),
  mappedLocation({ region: 'vul-gar', id: 'cidade-de-gron', name: 'Cidade de Gron', category: 'Cidade', summary: 'Cidade oriental registrada em território cultural de Vul’Gar.', description: 'O Atlas confirma um núcleo murado associado ao nome Gron. Não há fonte pública suficiente para ligá-lo a uma pessoa específica, definir clã governante ou população; a forma “cidade” reproduz a classificação cartográfica.', geography: 'Núcleo urbano em planalto seco, próximo a rotas de clãs e fontes dispersas.', relation: { label: 'Vul’Gar', to: '/reinos/vul-gar' } }),
  mappedLocation({ region: 'vul-gar', id: 'fortaleza-kring', name: 'Fortaleza Kring', category: 'Fortaleza', summary: 'Reduto oriental marcado entre os planaltos de Vul’Gar.', description: 'Uma estrutura fortificada aparece junto ao topônimo Kring. Sua casa, clã, função e relação com a Cidade de Gron são desconhecidos; qualquer vínculo de vassalagem seria invenção sem documento adicional.', geography: 'Fortaleza em elevação árida, voltada para corredores de aproximação do leste.', relation: { label: 'Vul’Gar', to: '/reinos/vul-gar' } }),
  mappedLocation({ region: 'vul-gar', id: 'acampamento-dos-clas', name: 'Acampamento dos Clãs', category: 'Acampamento', summary: 'Concentração de tendas assinalada no sul de Vul’Gar.', description: 'O raster representa um grande acampamento, mas não registra quais clãs o ocupam nem se a reunião é sazonal. O nome plural impede atribuir o lugar a uma única autoridade e reforça sua condição política não unificada.', geography: 'Planície seca apta a acampamentos móveis, próxima a rotas e pontos de água não nomeados.', relation: { label: 'Vul’Gar', to: '/reinos/vul-gar' } }),
  mappedLocation({ region: 'zharak', id: 'porto-da-serpente', name: 'Porto da Serpente', category: 'Porto', summary: 'Porto desenhado no limite entre os caminhos áridos e as águas meridionais.', description: 'O Atlas registra cais e embarcações junto ao topônimo, confirmando função portuária sem revelar governantes, mercadorias ou origem do emblema da serpente. Sua soberania permanece não registrada.', geography: 'Ancoradouro costeiro em margem árida, conectado a rotas de poços e caravanas.', relation: { label: 'Deserto de Zharak', to: '/locais/deserto-de-zharak' } }),
  mappedLocation({ region: 'zharak', id: 'oasis-perdido', name: 'Oásis Perdido', category: 'Oásis', summary: 'Fonte interior nomeada entre as rotas do Deserto de Zharak.', description: 'O símbolo mostra água e vegetação em zona desértica, mas o epíteto Perdido impede presumir acesso atual. Coordenadas são regionais, vazão e habitantes são desconhecidos, e relatos de cidade soterrada permanecem rumor.', geography: 'Depressão desértica com água e vegetação isoladas entre salinas e rocha.', relation: { label: 'Deserto de Zharak', to: '/locais/deserto-de-zharak' }, status: 'Localização aproximada' }),
  mappedLocation({ region: 'zharak', id: 'cidade-da-areia', name: 'Cidade da Areia', category: 'Cidade', summary: 'Cidade murada representada no setor oriental do Deserto de Zharak.', description: 'A carta confirma um assentamento de porte urbano cercado por dunas e caminhos de caravana. Nome antigo, população, poço fundador e forma de governo não foram registrados; o verbete não atribui soberania inexistente.', geography: 'Cidade em terreno árido, ligada a rotas de caravana e fontes não detalhadas.', relation: { label: 'Deserto de Zharak', to: '/locais/deserto-de-zharak' } }),
]
