import { record } from '../schema.js'

export const chronicleSites = [
  record({
    id: 'farol-das-sete-mares',
    name: 'Farol das Sete Marés',
    subtitle: 'A luz que responde às correntes',
    summary: 'Torre costeira de Eldemar cujas sete câmaras de luz orientam embarcações por corrente, calado e direção do vento.',
    description: 'Erguido sobre uma agulha de basalto ao sul do Porto de Eldemar, o Farol das Sete Marés não projeta uma única chama. Sete lanternas protegidas por lâminas de mica são abertas em combinações diferentes, formando um código que informa corrente, neblina, recife e autorização de entrada. O posto tornou-se indispensável depois que sucessivos naufrágios demonstraram que um simples ponto luminoso podia conduzir navios ao canal errado. Os nomes dos primeiros faroleiros foram perdidos num incêndio de arquivo; a instituição atual, porém, é documentada em livros de óleo, turnos e resgates.',
    category: 'Farol e posto marítimo',
    status: 'Operacional',
    kingdom: 'Eldemar',
    location: 'Costa meridional de Eldemar',
    period: 'Fundação contestada; operação atual documentada',
    climate: 'Marítimo, com sal, ventos fortes e neblina de corrente fria.',
    geography: 'Agulha de basalto ligada à costa por uma ponte estreita e alcançada por uma doca de maré baixa.',
    architecture: 'Torre octogonal de pedra escura, sete câmaras de mica e depósitos de óleo abaixo da linha principal de luz.',
    culture: 'Faroleiros são escolhidos entre pilotos aposentados, vidreiros e vigias; nenhuma família possui direito hereditário ao posto.',
    currentSituation: 'Duas câmaras precisam de nova mica, e a guilda debate se deve aceitar material de Kar-Dûm ou manter o vidro costeiro tradicional.',
    rumors: ['Uma oitava combinação de luzes indicaria uma rota de evacuação Rivs; a afirmação é baseada em rumor e não aparece no código público.'],
    narrativeImportance: 'Torna a navegação de Eldemar uma prática coletiva e oferece um ponto de observação para chegadas clandestinas, tempestades e alterações do Mar das Estrelas.',
    historicalSources: ['Livros de óleo do Conselho das Marés', 'Cadernos de pilotos do canal sul', 'Inventário das sete câmaras'],
    knowledgeStatus: 'documented',
    confidence: 'high',
    relations: [
      { label: 'Eldemar', to: '/reinos/eldemar' },
      { label: 'Porto de Eldemar', to: '/cidades/porto-de-eldemar' },
      { label: 'Mar das Estrelas', to: '/locais/mar-das-estrelas' },
      { label: 'Juramento do Horizonte', to: '/religioes/juramento-do-horizonte' },
    ],
  }),
  record({
    id: 'mosteiro-da-brasa-tardia',
    name: 'Mosteiro da Brasa Tardia',
    subtitle: 'Abrigo antes de doutrina',
    summary: 'Casa de passagem de Winterfeld onde calor, sopa e registro de viajantes precedem qualquer rito religioso.',
    description: 'O Mosteiro da Brasa Tardia ocupa uma garganta protegida do vento entre Winterheim e os vales setentrionais. Seus guardiões mantêm uma fornalha contínua, dormitórios baixos e um muro de pedras gravadas com as datas em que viajantes foram encontrados na neve. Embora associado à Vigília da Última Brasa, o abrigo não exige profissão de fé: a regra inscrita sobre a porta determina que perguntas só podem ser feitas depois que a pessoa estiver aquecida. A fundação exata é desconhecida, pois três tradições locais atribuem a primeira chama a comunidades diferentes.',
    category: 'Mosteiro e abrigo de estrada',
    status: 'Habitado',
    kingdom: 'Winterfeld',
    location: 'Garganta ocidental de Winterheim',
    period: 'Anterior ao registro unificado dos jarls',
    climate: 'Subártico, com ventos canalizados pela garganta e nevascas de curta visibilidade.',
    geography: 'Terraço rochoso próximo a uma fonte morna e a uma passagem sazonal.',
    architecture: 'Pedra encaixada, corredores baixos, teto de turfa e uma fornalha central ligada a bancos aquecidos.',
    culture: 'O serviço é temporário e inclui religiosos, guias, curandeiros e antigos devedores de abrigo.',
    currentSituation: 'O degelo abriu uma fissura no depósito oriental; monges e engenheiros aguardam uma inspeção conjunta de Winterheim e Kar-Dûm.',
    rumors: ['Algumas pedras do muro teriam nomes apagados de sobreviventes Nimbus; a leitura é contestada e não há inscrição autenticada.'],
    narrativeImportance: 'Materializa a lei de hospitalidade de Winterfeld e cria um encontro plausível entre viajantes, jarls, gigantes e expedições do norte.',
    historicalSources: ['Livro das Porções', 'Pedras de resgate do pátio', 'Atas de inspeção dos jarls'],
    knowledgeStatus: 'people-only',
    confidence: 'medium',
    relations: [
      { label: 'Winterfeld', to: '/reinos/winterfeld' },
      { label: 'Winterheim', to: '/cidades/winterheim' },
      { label: 'Vigília da Última Brasa', to: '/religioes/vigilia-ultima-brasa' },
      { label: 'Ordem da Última Brasa', to: '/faccoes/ordem-ultima-brasa' },
    ],
  }),
  record({
    id: 'arquivo-de-pedra',
    name: 'Arquivo de Pedra',
    subtitle: 'Onde toda falha recebe uma placa',
    summary: 'Repositório de Kar-Dûm que preserva projetos aprovados, erros de engenharia e os nomes de quem interrompeu obras perigosas.',
    description: 'O Arquivo de Pedra ocupa galerias secas acima de Thur-Kar e reúne milhares de placas de ardósia organizadas por salão, material e grau de risco. Ao contrário dos salões de glória, ele preserva obras recusadas, pontes que cederam e cálculos corrigidos; apagar uma falha é considerado mais vergonhoso do que cometê-la e registrá-la. O público pode consultar cópias de superfície, enquanto mapas de ventilação e lacres profundos permanecem conhecidos apenas pelos ofícios responsáveis. Uma ala inteira relativa aos Túneis Vazios foi perdida durante uma evacuação, e nenhuma reconstrução posterior é tratada como equivalente ao original.',
    category: 'Arquivo técnico',
    status: 'Consulta parcial',
    kingdom: 'Kar-Dûm',
    location: 'Galerias superiores de Thur-Kar',
    period: 'Ampliado após a Guerra dos Túneis Vazios',
    climate: 'Subterrâneo seco e estável, com controle rigoroso de fuligem e umidade.',
    geography: 'Galerias elevadas ligadas ao vazio central por pontes de serviço.',
    architecture: 'Nichos numerados, estantes de pedra inclinada, portas corta-fogo e canais de ventilação independentes.',
    culture: 'Aprendizes copiam relatórios de erro antes de receber autorização para assinar projetos próprios.',
    currentSituation: 'O Conselho dos Nove discute o acesso dos Seladores a placas que podem descrever estruturas do Véu.',
    rumors: ['Um índice apagado mencionaria um décimo salão; a alegação é contestada e o fragmento não foi apresentado à auditoria pública.'],
    narrativeImportance: 'Conecta ofício, memória e política de segurança, além de fornecer evidências materiais para investigações sobre Fraturas e Fulgarion.',
    historicalSources: ['Índice dos Nove Salões', 'Placas de falha pública', 'Catálogo posterior aos Túneis Vazios'],
    knowledgeStatus: 'people-only',
    confidence: 'high',
    relations: [
      { label: 'Kar-Dûm', to: '/reinos/kar-dum' },
      { label: 'Thur-Kar', to: '/cidades/thur-kar' },
      { label: 'Guerra dos Túneis Vazios', to: '/guerras/guerra-dos-tuneis-vazios' },
      { label: 'Vigia de Pedra', to: '/criaturas/vigia-de-pedra' },
    ],
  }),
  record({
    id: 'jardim-das-pontes-silenciosas',
    name: 'Jardim das Pontes Silenciosas',
    subtitle: 'Memória sem estátua',
    summary: 'Jardim memorial de Sylvaris onde pontes removíveis conduzem a clareiras dedicadas a comunidades deslocadas.',
    description: 'O Jardim das Pontes Silenciosas foi cultivado na margem externa de Lethariel para lembrar aldeias que acolheram perseguidos e depois desapareceram dos mapas públicos. Não existem estátuas individuais: cada clareira preserva espécies, sementes e materiais associados a uma comunidade, enquanto pequenas pontes são recolhidas durante períodos de luto ou quando descendentes pedem privacidade. Os nomes completos permanecem conhecidos apenas pelos Círculos e pelas famílias autorizadas. Visitantes recebem um roteiro público que explica a história sem revelar rotas de refúgio ainda utilizáveis.',
    category: 'Jardim memorial',
    status: 'Protegido',
    kingdom: 'Sylvaris',
    location: 'Margem externa de Lethariel',
    period: 'Organizado depois da Caça às Bruxas',
    climate: 'Úmido e ameno sob copa manejada.',
    geography: 'Clareiras ligadas por canais rasos e passarelas que podem ser removidas sem ferir raízes.',
    architecture: 'Pontes leves, bancos de madeira caída, placas vegetais e casas discretas para guardiões.',
    culture: 'O direito de lembrar não anula o direito de ocultar pessoas ainda vulneráveis.',
    currentSituation: 'Uma ponte permanece recolhida por decisão de famílias que identificaram buscas recentes por antigas rotas Bellatrix.',
    rumors: ['Canções afirmam que uma clareira responde à presença Kayler; os guardiões classificam a versão como interpretação poética.'],
    narrativeImportance: 'Expõe a tensão entre memória pública e proteção, dando consequência civil à perseguição sem transformar refugiados em decoração heroica.',
    historicalSources: ['Roteiro público dos Círculos', 'Catálogo botânico das clareiras', 'Atas de custódia com nomes omitidos'],
    knowledgeStatus: 'people-only',
    confidence: 'high',
    relations: [
      { label: 'Sylvaris', to: '/reinos/sylvaris' },
      { label: 'Lethariel', to: '/cidades/lethariel' },
      { label: 'Caça às Bruxas', to: '/historia/caca-bruxas' },
      { label: 'Crônicas Perdidas de Sylvaris', to: '/biblioteca/cronicas-perdidas-de-sylvaris' },
    ],
  }),
  record({
    id: 'mercado-dos-tres-ventos',
    name: 'Mercado dos Três Ventos',
    subtitle: 'Preço, procedência e passagem',
    summary: 'Feira de Valoria onde caravanas do rio, das planícies e do sudeste submetem pesos e contratos a uma auditoria comum.',
    description: 'O Mercado dos Três Ventos se reúne num campo elevado próximo a Valóris, no encontro das rotas fluvial, oriental e meridional. Toldos são organizados por procedência, não por riqueza, e toda balança precisa receber o selo temporário dos magistrados de peso antes da abertura. A feira ganhou importância durante anos de cheia, quando seus depósitos secos impediram que o comércio fosse concentrado dentro das muralhas da capital. Comunidades de Zharak e Vul’Gar mantêm intérpretes próprios e contestam taxas que a corte tenta apresentar como antigas.',
    category: 'Feira e entreposto',
    status: 'Sazonal e ativo',
    kingdom: 'Valoria',
    location: 'Planície elevada a sudeste de Valóris',
    period: 'Registro contínuo desde a Era das Coroas',
    climate: 'Temperado, exposto a ventos secos do leste e chuvas do corredor fluvial.',
    geography: 'Terraço natural acima da zona de cheia, junto a três estradas e um cais sazonal.',
    architecture: 'Depósitos de tijolo, pavilhões desmontáveis, torre de pesos e cisternas públicas.',
    culture: 'Contratos são lidos em mais de um idioma quando envolvem comunidades de fronteira.',
    currentSituation: 'A próxima feira ocorrerá sob auditoria ampliada depois da descoberta de pesos adulterados em dois armazéns nobres.',
    rumors: ['Agentes da Corte de Cinza comprariam grão sob nomes falsos; a acusação ainda não possui prova pública.'],
    narrativeImportance: 'Mostra como alimento, idioma e crédito conectam Valoria ao oriente, oferecendo cenário para diplomacia, espionagem e crises de abastecimento.',
    historicalSources: ['Selos anuais dos magistrados', 'Contratos trilíngues preservados', 'Cadastros dos depósitos elevados'],
    knowledgeStatus: 'documented',
    confidence: 'high',
    relations: [
      { label: 'Valoria', to: '/reinos/valoria' },
      { label: 'Valóris', to: '/cidades/valoris' },
      { label: 'Deserto de Zharak', to: '/locais/deserto-de-zharak' },
      { label: 'Corte de Cinza', to: '/faccoes/corte-de-cinza' },
    ],
  }),
  record({
    id: 'torre-da-chuva-negra',
    name: 'Torre da Chuva Negra',
    subtitle: 'Um observatório confundido com mau presságio',
    summary: 'Ruína de fronteira de Ravenhold cujos coletores escurecidos registravam chuva, poeira e fumaça antes das marchas.',
    description: 'A Torre da Chuva Negra ergue-se num planalto oriental, distante o bastante das estradas principais para ter sobrevivido à expansão de Ravencastle. Canais de cobre conduziam chuva a vasos graduados, enquanto placas claras recolhiam poeira transportada do leste; quando fuligem de grandes incêndios tingia a água, vigias baixavam um estandarte negro. Crônicas militares posteriores transformaram o procedimento em profecia de guerra. A função meteorológica é documentada, mas o construtor e a data exata permanecem não registrados.',
    category: 'Observatório em ruínas',
    status: 'Estável sob inspeção',
    kingdom: 'Ravenhold',
    location: 'Planalto oriental de Ravenhold',
    period: 'Provavelmente anterior à Casa Corven',
    climate: 'Continental e seco, com tempestades rápidas e poeira trazida das fronteiras.',
    geography: 'Esporão de rocha sobre uma bacia rasa, visível de antigas estradas de patrulha.',
    architecture: 'Torre cilíndrica, canais de cobre corroído, nichos de medição e plataforma de sinais.',
    culture: 'Veteranos reformistas usam o lugar para ensinar a diferença entre observação, ordem militar e propaganda.',
    currentSituation: 'Uma equipe civil reabriu os coletores para comparar incêndios reais com relatos de ataques de fronteira.',
    rumors: ['Contrabandistas dizem ouvir chuva dentro da torre em noites secas; nenhuma inspeção confirmou o fenômeno.'],
    narrativeImportance: 'Fornece evidência contra operações de bandeira falsa e revela como dados comuns podem ser convertidos em presságio político.',
    historicalSources: ['Placas meteorológicas recuperadas', 'Ordens de sinalização das legiões', 'Relatório civil de estabilização'],
    knowledgeStatus: 'documented',
    confidence: 'medium',
    relations: [
      { label: 'Ravenhold', to: '/reinos/ravenhold' },
      { label: 'Ravencastle', to: '/cidades/ravencastle' },
      { label: 'Vigília do Sol Negro', to: '/religioes/vigilia-sol-negro' },
      { label: 'Códice dos Estandartes Baixos', to: '/biblioteca/codice-dos-estandartes-baixos' },
    ],
  }),
]
