import { record } from '../schema.js'
import { locationDossiers } from '../places/dossiers.js'

const locationRecords = [
  record({ id: 'floresta-antiga', name: 'Floresta Antiga', subtitle: 'Onde caminhos guardam memória', summary: 'Grande floresta do oeste, lar de Sylvaris e refúgio de Sirius durante a perseguição.', description: 'A floresta reúne zonas manejadas, áreas sagradas e regiões nunca ocupadas. Trilhas mudam porque pontes são recolhidas, vegetação cresce rápido e guardiões desviam invasores — não porque o território ignore as leis naturais.', image: '/assets/images/locations/jornada-floresta-antiga-banner.webp', thumbnail: '/assets/images/locations/jornada-floresta-antiga-card.webp', category: 'Floresta', status: 'Protegida', kingdom: 'Sylvaris', location: 'Oeste de Avernor', relations: [{ label: 'Sylvaris', to: '/reinos/sylvaris' }] }),
  record({ id: 'mar-das-estrelas', name: 'Mar das Estrelas', subtitle: 'A rota de Eldemar', summary: 'Mar meridional conhecido por plâncton luminoso, bancos de neblina e rotas comerciais disputadas.', description: 'O brilho noturno permite navegar sem tochas em algumas estações, mas confunde a percepção de distância. Correntes frias trazem grandes animais, incluindo os avistamentos atribuídos ao kraken.', category: 'Mar', status: 'Navegado', location: 'Sul de Avernor', relations: [{ label: 'Eldemar', to: '/reinos/eldemar' }, { label: 'Kraken de Eldemar', to: '/criaturas/kraken-de-eldemar' }] }),
  record({ id: 'deserto-de-zharak', name: 'Deserto de Zharak', subtitle: 'Sal, vento e cidades de poço', summary: 'Terras áridas cujo povoamento depende de aquíferos antigos e rotas de sal.', description: 'Comunidades constroem ao redor de poços compartilhados e usam torres de vento para resfriar depósitos. Guerras abertas são raras perto da água, pois contaminar um aquífero condenaria vencedores e vencidos.', category: 'Deserto', status: 'Habitado', location: 'Sudeste de Avernor', relations: [{ label: 'Lobo de Vidro', to: '/criaturas/lobo-de-vidro' }, { label: 'Espelho de Sal', to: '/portais/espelho-de-sal' }] }),
  record({ id: 'arquipelago-das-brumas', name: 'Arquipélago das Brumas', subtitle: 'Ilhas sem uma só bandeira', summary: 'Conjunto de ilhas que abriga pescadores, observatórios, contrabandistas e portos independentes.', description: 'Canais rasos impedem grandes frotas e favorecem pilotos locais. A ausência de autoridade única cria liberdade comercial, mas também torna resgates e julgamentos dependentes de pactos entre vilas.', category: 'Arquipélago', status: 'Fragmentado', location: 'Sudoeste de Avernor', relations: [{ label: 'Eldemar', to: '/reinos/eldemar' }] }),
  record({ id: 'terras-sombrias', name: 'Terras Sombrias', subtitle: 'A fronteira marcada pela peste', summary: 'Região oriental abandonada após uma doença que deixou cidades vazias e solos contaminados por metais.', description: 'Histórias sobre mortos-vivos exageram um perigo real: minas abertas contaminaram água e a peste eliminou comunidades inteiras. Expedições usam máscaras de carvão, analisam poços e evitam ruínas instáveis.', category: 'Zona interditada', status: 'Acesso restrito', location: 'Extremo leste', relations: [{ label: 'Necromancia', to: '/necromancia/necromancia' }] }),
  record({ id: 'mar-interior', name: 'Mar Interior', subtitle: 'A água entre as coroas', summary: 'Sistema de lagos e estreitos que conecta rotas de Valoria, Sylvaris e Kar-Dûm.', description: 'Pontes e balsas fizeram do Mar Interior o principal corredor econômico do continente. As margens guardam ruínas Rivs e antigos postos das Doze Legiões.', category: 'Mar interior', status: 'Navegado', location: 'Centro-oeste de Avernor', relations: [{ label: 'Arquivo Submerso', to: '/lendas/arquivo-submerso' }] }),
]

export const locations = locationRecords.map((location) => ({ ...location, ...locationDossiers[location.id] }))
