import { record } from '../schema.js'
import { warDossiers } from './dossiers.js'

const warRecords = [
  record({ id: 'guerra-dos-tres-herdeiros', name: 'Guerra dos Três Herdeiros', subtitle: 'O conflito que dividiu as Doze Legiões', summary: 'Um século de campanhas sucessórias destruiu o reino indiviso e transformou governadores em soberanos regionais.', description: 'Aldren, Kaelor e Theron, filhos de Edric Averen, herdaram exércitos, mas não legitimidade suficiente. Nenhum lado reuniu força para vencer sem devastar as terras que pretendia governar. Depois de milhões de mortes e da exaustão dos herdeiros, Marcellus Veyron reunificou o que restava.', category: 'Guerra sucessória', status: 'Encerrada', period: 'Ano 0–100', era: 'Grande Guerra', location: 'Todo o continente', belligerents: ['Forças de Aldren Averen', 'Forças de Kaelor Averen', 'Forças de Theron Averen'], outcome: 'Devastação continental e ascensão de Marcellus Veyron', causes: ['Morte de Edric sem sucessor declarado', 'Divisão das Doze Legiões', 'Disputa pelo controle de celeiros e estradas'], phases: ['Campanhas dos três estandartes', 'Cerco prolongado das rotas centrais', 'Exaustão das casas Averen', 'Reunificação por Veyron'], consequences: ['Milhões de mortos', 'Fim da unidade política legítima', 'Precedentes para dinastias regionais'], civilianImpact: ['Fomes recorrentes', 'Deslocamento de aldeias inteiras', 'Estradas destruídas para impedir exércitos'], events: ['Cisma das Doze Legiões', 'Cerco dos Três Estandartes', 'Tratado das Cinzas'], relations: [{ label: 'Genealogia Averen', to: '/genealogias/averen' }, { label: 'A Grande Guerra', to: '/historia/grande-guerra' }] }),
  record({ id: 'guerra-da-cinza-branca', name: 'Guerra da Cinza Branca', subtitle: 'A perseguição transformada em política continental', summary: 'Campanhas coordenadas pelo Conselho dos Sete Reis contra as três linhagens bruxas.', description: 'O Edito da Cinza Branca exigiu registro, serviço obrigatório e entrega de crianças. Os Nimbus enfrentaram os exércitos e foram destruídos; os Rivs evacuaram bibliotecas e desapareceram. Redes civis esconderam perseguidos. A guerra terminou após a batalha final de Normus, quando quase não restavam alvos públicos.', category: 'Perseguição e guerra civil', status: 'Encerrada — consequências ativas', period: 'Ano 628–704', era: 'Caça às Bruxas', location: 'Avernor central e oriental', belligerents: ['Conselho dos Sete Reis', 'Casas Kayler, Nimbus e Rivs', 'Redes de refúgio'], outcome: 'Quase desaparecimento das linhagens bruxas', causes: ['Medo político do poder hereditário', 'Interesse em terras e arquivos das Casas', 'Recusa ao registro e ao serviço forçado'], phases: ['Edito da Cinza Branca', 'Resistência Nimbus', 'Evacuação Rivs', 'Cerco da Fortaleza do Véu', 'Batalha final de Normus'], consequences: ['Nimbus considerados extintos', 'Rivs desaparecidos', 'Sirius mantido em segredo por cinco séculos'], civilianImpact: ['Crianças separadas de famílias', 'Fortalezas convertidas em refúgios', 'Arquivos e identidades deliberadamente apagados'], events: ['Edito da Cinza Branca', 'Queda do Arquivo Rivs', 'Cerco da Fortaleza do Véu'], relations: [{ label: 'Casa Kayler', to: '/casas/kayler' }, { label: 'Caça às Bruxas', to: '/historia/caca-bruxas' }] }),
  record({ id: 'batalha-das-aguas-negras', name: 'Batalha das Águas Negras', subtitle: 'A noite em que Eldemar apagou os faróis', summary: 'Confronto naval decidido por pilotos costeiros, marés e informação falsa, não por superioridade numérica.', description: 'Uma frota de saqueadores tentou tomar as docas de Eldemar durante lua nova. O Conselho das Marés apagou faróis oficiais e acendeu sinais em recifes desabitados. Pequenos navios conduziram parte da frota invasora para águas rasas, onde a maré descendente a imobilizou. O plano salvou o porto, mas destruiu vilas costeiras usadas como isca, dívida ainda debatida.', category: 'Batalha naval', status: 'Encerrada', period: 'Ano 552', era: 'Era das Coroas', location: 'Costa de Eldemar', belligerents: ['Frota de Eldemar', 'Liga das Brumas'], outcome: 'Vitória de Eldemar com perdas civis', causes: ['Tentativa de capturar os estaleiros e o monopólio cartográfico'], phases: ['Apagamento dos faróis', 'Desvio para recifes', 'Bloqueio pela maré baixa'], consequences: ['Sobrevivência do porto', 'Poder ampliado do Conselho das Marés'], civilianImpact: ['Vilas costeiras destruídas como parte do engodo', 'Reparações ainda incompletas'], relations: [{ label: 'Eldemar', to: '/reinos/eldemar' }] }),
  record({ id: 'guerra-dos-tuneis-vazios', name: 'Guerra dos Túneis Vazios', subtitle: 'Quando Kar-Dûm lutou contra a própria expansão', summary: 'Campanha subterrânea para conter colapsos, gases e criaturas após salões rivais romperem lacres antigos.', description: 'Não houve exército inimigo único. A guerra recebeu esse nome porque exigiu mobilização total: engenheiros fecharam galerias, soldados evacuaram bairros e curadores trataram intoxicações. O conflito terminou com o Código das Profundezas, que exige consenso de três salões antes de abrir um túnel ancestral.', category: 'Crise subterrânea', status: 'Encerrada', period: 'Ano 487–491', era: 'Era das Coroas', location: 'Kar-Dûm', belligerents: ['Nove Salões', 'Ameaças subterrâneas'], outcome: 'Criação do Código das Profundezas', causes: ['Competição mineral entre salões', 'Rompimento de lacres sem Escuta da Pedra'], phases: ['Primeiros colapsos', 'Evacuação dos bairros baixos', 'Selamento coordenado'], consequences: ['Código das Profundezas', 'Limite político à expansão'], civilianImpact: ['Intoxicação de mineiros', 'Perda de moradias e aquedutos'], relations: [{ label: 'Kar-Dûm', to: '/reinos/kar-dum' }] }),
  record({ id: 'guerra-dos-tronos', name: 'Guerra dos Tronos', subtitle: 'Quando as coroas disputaram as três Correntes', summary: 'Conflito da Era das Coroas em que reis tentaram obter exclusividade sobre Kayler, Nimbus e Rivs.', description: 'A guerra começou por pactos de proteção que escondiam exigências de serviço. Normus recusou todos os tronos, defendeu Kar-Dûm durante um cerco subterrâneo e depois Sylvaris contra invasores orcs contratados por intermediários humanos. A atribuição de culpa coletiva aos orcs é falsa: clãs distintos combateram em lados diferentes.', category: 'Guerra continental', status: 'Encerrada', period: 'Ano 566–612', era: 'Era das Coroas', location: 'Rotas centrais, Kar-Dûm e Sylvaris', belligerents: ['Coroas humanas rivais', 'Forças de Kar-Dûm e Sylvaris', 'Clãs orcs contratados e aliados'], outcome: 'Nenhuma coroa controlou as três Casas', causes: ['Competição pelo apoio dos bruxos', 'Disputa de passagens e metais', 'Tratados secretos incompatíveis'], phases: ['Guerra diplomática das cortes', 'Defesa de Kar-Dûm', 'Invasões contra Sylvaris', 'Juramento de Normus'], consequences: ['Normus nomeado Cavaleiro de Honra', 'Medo das coroas prepara a Caça às Bruxas', 'Tratados orcs passam a exigir identidade dos contratantes'], civilianImpact: ['Fechamento de rotas de alimento', 'Aldeias de fronteira deslocadas', 'Clãs orcs culpados coletivamente por decisões humanas'], relations: [{ label: 'Normus Kayler', to: '/personagens/normus-kayler' }, { label: 'Era das Coroas', to: '/historia/era-coroas' }] }),
]

export const wars = warRecords.map((war) => {
  const { additionalRelations = [], ...details } = warDossiers[war.id]
  return { ...war, ...details, relations: [...war.relations, ...additionalRelations] }
})
