import { record } from '../schema.js'
import { artifactDossiers } from '../items/dossiers.js'

const artifactRecords = [
  record({ id: 'espada-da-trovoada', name: 'Fulgarion, a Espada dos Sete Trovões', subtitle: 'A lâmina herdada de Normus', summary: 'Espada deixada para Sirius, construída para conduzir — e não criar — a magia de tempestade dos Kayler.', description: 'A lâmina contém filamentos de prata meteórica que distribuem carga e impedem que ela atravesse o braço do portador. Suas sete manifestações culminam na Porta da Tempestade. Sem um bruxo Kayler, é apenas uma espada pesada e bem forjada; sobrecarga derrete os filamentos e pode ferir todos ao redor.', category: 'Arma arcana e Relíquia', status: 'Em posse de Sirius', origin: 'Forjas de Kar-Dûm e acabamento de Normus', location: 'Com Sirius', period: 'Era das Coroas', abilities: ['Despertar', 'Passo Celeste', 'Corrente Partida', 'Céu Descendente', 'Tempestade Interior', 'Julgamento Violeta', 'Porta da Tempestade'], relations: [{ label: 'Registro entre as Cinco Relíquias', to: '/reliquias/fulgarion' }, { label: 'Sirius Kayler', to: '/personagens/sirius-kayler' }, { label: 'Normus Kayler', to: '/personagens/normus-kayler' }], curiosities: ['As marcas da bainha registram reparos, não vitórias.'] }),
  record({ id: 'adaga-do-passo-velado', name: 'Adaga do Passo Velado', subtitle: 'A lâmina rúnica de Elara', summary: 'Adaga élfica capaz de transportar Elara por distâncias curtas até pontos visíveis ou previamente marcados.', description: 'Runas gravadas no metal dobram a distância por um instante. A adaga não atravessa ferro meteórico e não pode levar grandes cargas. Cada salto retira calor do corpo da portadora; três usos rápidos podem causar perda de consciência.', category: 'Artefato rúnico', status: 'Ativo', origin: 'Sylvaris', location: 'Com Elara', period: 'Era atual', relations: [{ label: 'Elara', to: '/personagens/elara' }], curiosities: ['A bainha contém sais aquecedores para reduzir o risco de hipotermia.'] }),
  record({ id: 'medalhao-da-folha-partida', name: 'Medalhão da Folha Partida', subtitle: 'Sinal do pacto entre Kayler e Sylvaris', summary: 'Medalhão élfico deixado por Normus entre os pertences de Sirius.', description: 'Duas metades de prata vegetal formam uma folha atravessada por um raio. O objeto não concede magia; serve como prova reconhecida pelos guardiões de Sylvaris. Uma das inscrições permanece cifrada e depende da metade conservada pela Rainha.', category: 'Insígnia diplomática', status: 'Preservado', origin: 'Sylvaris', location: 'Com Sirius', period: 'Caça às Bruxas', relations: [{ label: 'Pacto dos Descendentes', to: '/lendas/pacto-dos-descendentes' }, { label: 'Sirius Kayler', to: '/personagens/sirius-kayler' }] }),
  record({ id: 'martelo-de-orun', name: 'Martelo de Orun', subtitle: 'Padrão das nove forjas', summary: 'Ferramenta cerimonial usada para calibrar pesos e resolver disputas entre os salões de Kar-Dûm.', description: 'O martelo não é uma arma mágica. Sua importância vem da precisão: a cabeça mantém massa e equilíbrio mesmo após séculos de reparo. Réplicas comerciais são comparadas ao original uma vez por ano.', category: 'Relíquia cívica', status: 'Em uso cerimonial', origin: 'Kar-Dûm', location: 'Thur-Kar', period: 'Era da Magia', relations: [{ label: 'Kar-Dûm', to: '/reinos/kar-dum' }] }),
  record({ id: 'carta-de-normus', name: 'Carta de Normus', subtitle: 'Palavras para um filho sem lembranças', summary: 'Documento selado entregue a Sirius com ouro, espada, medalhão e pertences do pai.', description: 'A carta explica parte da perseguição e pede que Sirius não confunda vingança com memória. Trechos finais usam uma cifra Bellatrix, possivelmente para proteger a localização de sobreviventes. O Arquivo registra sua existência, mas não publica o texto integral por escolha de Sirius.', category: 'Documento pessoal', status: 'Parcialmente decifrado', origin: 'Normus Kayler', location: 'Com Sirius', period: 'Caça às Bruxas', relations: [{ label: 'Normus Kayler', to: '/personagens/normus-kayler' }, { label: 'Namídia Bellatrix', to: '/personagens/namidia-bellatrix' }] }),
]

export const artifacts = artifactRecords.map((artifact) => ({ ...artifact, ...artifactDossiers[artifact.id] }))
