import { record } from '../schema.js'
import { applyArchiveDossiers, legendArchiveDossiers } from '../editorial/archiveDossiers.js'

const legendRecords = [
  record({ id: 'noite-das-doze-adagas', name: 'A Noite das Doze Adagas', subtitle: 'Regicídio ou última defesa?', summary: 'Relato sobre os doze conselheiros que encerraram a tirania de Marcellus Veyron e desapareceram antes do amanhecer.', description: 'Versões populares afirmam que doze lâminas atingiram o rei ao mesmo tempo. Arquivos médicos indicam menos ferimentos, sugerindo que “doze adagas” representa o conselho inteiro. A ausência das armas permitiu que cada reino reivindicasse um herói entre os conspiradores.', category: 'Lenda política', status: 'Parcialmente comprovada', period: 'Ano 158', location: 'Antiga capital de Avernor', relations: [{ label: 'A Queda da Coroa', to: '/historia/queda-coroa' }] }),
  record({ id: 'arquivo-submerso', name: 'O Arquivo Submerso', subtitle: 'A última memória dos Rivs', summary: 'História de uma biblioteca escondida sob águas que só recuam diante de alguém da linhagem Rivs.', description: 'Mapas Rivs indicam depósitos de documentos em ilhas fluviais, mas nenhum confirma uma biblioteca submarina. É possível que “águas que recuam” seja instrução para operar comportas. A lenda persiste porque caçadores nunca recuperaram os registros centrais da família.', category: 'Lenda arcana', status: 'Não localizado', period: 'Caça às Bruxas', location: 'Mar Interior', relations: [{ label: 'Casa Rivs', to: '/casas/rivs' }] }),
  record({ id: 'pacto-dos-descendentes', name: 'O Pacto dos Descendentes', subtitle: 'A promessa de Normus e Aelwen', summary: 'Acordo reservado entre Normus e Aelwen que protegeu o descendente Kayler sem transformar qualquer herdeiro em propriedade do outro.', description: 'O registro público confirma abrigo concedido a Sirius e a existência de obrigações ainda vigentes, mas não publica seu alcance, condições ou contrapartidas. Canções românticas o tratam como promessa de casamento; essa interpretação não consta nos fragmentos autênticos. Elara e Sirius preservam liberdade de escolha. Qualquer dever adicional permanece desconhecido fora da custódia autorizada de Sylvaris.', category: 'Pacto secreto', status: 'Ativo e incompleto', truthStatus: 'redacted', knowledgeStatus: 'secret', period: 'Fim da Era das Coroas', location: 'Sylvaris', relations: [{ label: 'Normus Kayler', to: '/personagens/normus-kayler' }, { label: 'Rainha Aelwen', to: '/personagens/rainha-aelwen' }, { label: 'Elara', to: '/personagens/elara' }, { label: 'Sirius Kayler', to: '/personagens/sirius-kayler' }] }),
  record({ id: 'sinos-do-mar-de-cinzas', name: 'Os Sinos do Mar de Cinzas', subtitle: 'O aviso que sobe da água', summary: 'Marinheiros relatam sinos sob a superfície antes de nevoeiros que desorientam bússolas.', description: 'O som pode vir de rochas ocas movidas por correntes. Ainda assim, mapas de Eldemar tratam o fenômeno como aviso confiável e exigem redução de velas. A lenda ganhou tom sobrenatural após um navio reaparecer sem tripulação.', category: 'Lenda marítima', status: 'Fenômeno observado', location: 'Mar de Cinzas', relations: [{ label: 'Eldemar', to: '/reinos/eldemar' }] }),
  record({
    id: 'barca-sem-remador',
    name: 'A Barca sem Remador',
    subtitle: 'O resgate que ninguém reivindicou',
    summary: 'Pilotos de Eldemar narram que uma pequena barca surge durante tempestades para marcar o canal seguro e desaparece antes do amanhecer.',
    description: 'A Barca sem Remador aparece em depoimentos separados por quase dois séculos: uma embarcação baixa, com vela recolhida e uma lanterna protegida, cruzaria à frente de navios perdidos até o Farol das Sete Marés. Nenhum relato confiável afirma que a barca navegue contra corrente ou sem tripulação; a expressão provavelmente nasceu porque ninguém era visto acima da amurada. Livros de resgate registram embarcações de pilotos que operavam sem identificação para evitar represálias de contrabandistas. A tradição, portanto, pode preservar uma rede humana apagada dos registros, embora sua continuidade até o presente seja baseada em rumor.',
    category: 'Lenda marítima',
    status: 'Contestada',
    truthStatus: 'disputed',
    knowledgeStatus: 'rumor',
    confidence: 'low',
    period: 'Relatos entre a Era das Coroas e 1204 d.C.',
    location: 'Costa de Eldemar',
    archivalOverview: 'O Arquivo conserva a lenda como memória de resgates anônimos, sem declarar uma embarcação sobrenatural ou um piloto imortal.',
    provenance: 'Cinco livros de bordo citam uma luz baixa conduzindo navios; apenas dois descrevem uma barca, e nenhum foi escrito pela mesma tripulação.',
    publicKnowledge: ['O padrão de luz corresponde a sinais costeiros antigos e os relatos se concentram no canal meridional.'],
    knowledgeGaps: ['A identidade dos pilotos, a quantidade de embarcações e a existência de uma tradição organizada permanecem não registradas.'],
    culturalReadings: ['Marinheiros a tratam como dívida de resgate; sacerdotes do Horizonte falam em promessa que continua navegando.'],
    historicalSources: ['Livros de resgate de Eldemar', 'Depoimentos do cais sul', 'Códigos antigos de lanterna'],
    disputedClaims: ['A afirmação de que a barca atravessa tempestades sem tripulação não possui testemunho próximo o bastante para confirmação.'],
    narrativeImportance: 'Oferece uma lenda sobre solidariedade clandestina e permite investigar quem foi apagado dos registros marítimos.',
    imageBrief: 'Barca pequena vista de um navio maior durante tempestade, lanterna baixa e Farol das Sete Marés distante, sem fantasma visível.',
    sections: [
      { title: 'O padrão dos avistamentos', body: 'As ocorrências preservadas compartilham canal, luz baixa e desaparecimento antes da identificação, mas divergem sobre casco, cor e distância.' },
      { title: 'Hipótese dos pilotos ocultos', body: 'Códigos de resgate demonstram que pilotos já navegaram sem brasão para proteger famílias ameaçadas por redes de contrabando.' },
      { title: 'O que permanece desconhecido', body: 'Não existe casco recuperado, lista de tripulantes ou cadeia documental que prove continuidade entre os relatos.' },
      { title: 'Leitura dos cais', body: 'Tripulações deixam uma medida de óleo no farol depois de sobreviver a uma tormenta, gesto de gratidão e não tributo obrigatório.' },
    ],
    relations: [
      { label: 'Eldemar', to: '/reinos/eldemar' },
      { label: 'Farol das Sete Marés', to: '/locais/farol-das-sete-mares' },
      { label: 'Juramento do Horizonte', to: '/religioes/juramento-do-horizonte' },
    ],
  }),
  record({
    id: 'sino-sob-a-geleira',
    name: 'O Sino sob a Geleira',
    subtitle: 'Um som contado pelos gigantes',
    summary: 'Cantos do norte descrevem um toque grave sob o gelo quando uma passagem antiga se torna perigosa.',
    description: 'O Sino sob a Geleira não é conhecido por observação pública direta. Comunidades gigantes de dois vales preservam cantos sobre uma pedra sonora enterrada pelo avanço do gelo, capaz de devolver vibrações diferentes quando a geleira se rompe por dentro. Guias humanos passaram a chamar o fenômeno de sino, embora os cantos não descrevam metal, torre ou mão que o faça soar. Medições recentes confirmam estalos de baixa frequência antes de alguns colapsos, mas não localizam um objeto. A versão de que o som anuncia a morte de reis surgiu em baladas meridionais e é rejeitada pelos povos que conservam a tradição.',
    category: 'Tradição dos gigantes',
    status: 'Conhecida apenas por determinado povo',
    truthStatus: 'documented',
    knowledgeStatus: 'people-only',
    confidence: 'medium',
    period: 'Anterior aos calendários de Winterfeld',
    location: 'Geleiras setentrionais',
    archivalOverview: 'O registro público apresenta a tradição como conhecimento territorial gigante parcialmente apoiado por observação geológica.',
    provenance: 'Dois ciclos de canto foram traduzidos com consentimento dos vales; sensores de Winterfeld registraram vibrações semelhantes, sem identificar sua fonte exata.',
    publicKnowledge: ['O gelo profundo produz sons antes de certas rupturas, e guias gigantes ajustam rotas segundo ritmo, direção e duração.'],
    knowledgeGaps: ['A localização da pedra sonora, se ela existe como objeto distinto, permanece conhecida apenas pelos cantores ou pode ter sido perdida.'],
    culturalReadings: ['Gigantes leem o som como linguagem do território; humanos tendem a convertê-lo em presságio político.'],
    historicalSources: ['Cantos do Vale Sonoro', 'Cadernos de guias de Winterfeld', 'Medições do degelo de 1203'],
    disputedClaims: ['Não há evidência de que o fenômeno responda a coroas, guerras ou à presença de Vyrasul.'],
    narrativeImportance: 'Reconhece conhecimento gigante sem apropriá-lo e pode orientar expedições quando instrumentos humanos oferecem dados incompletos.',
    imageBrief: 'Corte visual de geleira azul profunda com gigantes escutando a pedra pelo chão, nenhuma torre ou sino metálico literal.',
    sections: [
      { title: 'A tradição preservada', body: 'Os cantos descrevem escuta coletiva, comparação entre invernos e responsabilidade de fechar uma passagem antes do desastre.' },
      { title: 'O registro de Winterfeld', body: 'Vigias confirmam sons graves e deslocamentos internos, mas seus instrumentos cobrem apenas uma fração das geleiras.' },
      { title: 'Limite de acesso', body: 'Versos, nomes de rotas e locais de escuta não foram publicados porque pertencem às comunidades que os utilizam.' },
      { title: 'A lenda meridional', body: 'Baladas sobre reis mortos são tardias, deslocadas do norte e rejeitadas como apropriação por cantores gigantes.' },
    ],
    relations: [
      { label: 'Winterfeld', to: '/reinos/winterfeld' },
      { label: 'Gigantes', to: '/povos/gigantes' },
      { label: 'Mosteiro da Brasa Tardia', to: '/locais/mosteiro-da-brasa-tardia' },
      { label: 'Vyrasul', to: '/criaturas/vyrasul' },
    ],
  }),
  record({
    id: 'nona-porta',
    name: 'A Nona Porta',
    subtitle: 'A passagem que só existe quando uma obra deve parar',
    summary: 'Aprendizes de Kar-Dûm contam que toda grande escavação possui uma nona saída reservada à decisão de abandonar o trabalho.',
    description: 'A lenda da Nona Porta nasceu da arquitetura redundante de Kar-Dûm. Salões públicos costumam possuir oito acessos nomeados, mas histórias de oficina afirmam que mestres responsáveis sempre mantêm uma nona passagem fora das plantas cerimoniais. O Arquivo de Pedra confirma rotas de evacuação omitidas de cópias abertas, porém não reconhece uma porta universal nem um túnel que conecte todos os salões. Para aprendizes, “abrir a nona porta” significa aceitar que custo, orgulho e tradição não justificam continuar uma obra insegura. Seladores reinterpretaram a expressão como acesso secreto ao Véu; essa leitura permanece contestada e produziu invasões perigosas.',
    category: 'Lenda de ofício',
    status: 'Metáfora documentada; passagem contestada',
    truthStatus: 'disputed',
    knowledgeStatus: 'people-only',
    confidence: 'medium',
    period: 'Posterior aos primeiros códigos dos Nove Salões',
    location: 'Kar-Dûm',
    archivalOverview: 'O Arquivo registra a Nona Porta como princípio de segurança e tradição de oficina, não como estrutura única comprovada.',
    provenance: 'Provérbios, placas de evacuação e atas de obras interrompidas demonstram uso contínuo da expressão entre ofícios.',
    publicKnowledge: ['Rotas de socorro são omitidas de mapas públicos e toda obra profunda precisa prever abandono seguro.'],
    knowledgeGaps: ['A origem do número nove e a primeira oficina a usar a expressão estão perdidas.'],
    culturalReadings: ['Engenheiros falam em humildade material; Seladores procuram um limiar literal que os arquivos não confirmam.'],
    historicalSources: ['Código das Profundezas', 'Placas de obras interrompidas', 'Provérbios dos aprendizes'],
    disputedClaims: ['Nenhuma evidência sustenta uma porta capaz de atravessar todos os salões ou tocar diretamente o Véu.'],
    narrativeImportance: 'Converte segurança em valor cultural e cria conflito entre leitura técnica, ambição ritual e exploração de ruínas.',
    imageBrief: 'Galeria anã com oito arcos iluminados e uma abertura de evacuação discreta, ferramentas abandonadas com ordem e nenhuma porta mágica.',
    sections: [
      { title: 'A expressão de oficina', body: 'Mestres a empregam quando uma equipe precisa suspender trabalho sem transformar retirada em desonra.' },
      { title: 'As rotas omitidas', body: 'Passagens reais existem, mas sua posição permanece conhecida apenas pelos ofícios responsáveis para impedir sabotagem.' },
      { title: 'A leitura dos Seladores', body: 'A busca por uma estrutura universal ignora diferenças de idade, função e engenharia entre os salões.' },
      { title: 'O ensinamento preservado', body: 'A lenda recorda que a obra mais valiosa pode ser a saída construída antes que alguém precise dela.' },
    ],
    relations: [
      { label: 'Kar-Dûm', to: '/reinos/kar-dum' },
      { label: 'Arquivo de Pedra', to: '/locais/arquivo-de-pedra' },
      { label: 'Guerra dos Túneis Vazios', to: '/guerras/guerra-dos-tuneis-vazios' },
      { label: 'Seladores', to: '/faccoes/seladores' },
    ],
  }),
]

export const legends = applyArchiveDossiers(legendRecords, legendArchiveDossiers)
