import { record } from '../schema.js'
import { houseDossiers } from './dossiers.js'

const houseRecords = [
  record({ id: 'kayler', name: 'Casa Kayler', subtitle: 'Senhores da Tempestade', summary: 'A mais célebre linhagem bruxa, associada a tempestades, raios e domínio arcano superior.', description: 'A Casa Kayler entendia poder como obrigação de intervenção: seus membros escoltavam refugiados, encerravam cercos e enfrentavam criaturas que exércitos evitavam. Essa visibilidade trouxe prestígio e os tornou o primeiro alvo da perseguição. A magia Kayler é hereditária; treino refina o dom, mas jamais o cria em quem não nasceu na linhagem.', category: 'Linhagem bruxa', status: 'Quase extinta', lineage: 'Kayler', origin: 'Planícies centrais', traits: 'Cabelos brancos, olhos violetas e afinidade com tempestades', motto: 'O céu se curva, mas o sangue permanece.', members: ['Normus Kayler', 'Sirius Kayler'], relations: [{ label: 'Normus Kayler', to: '/personagens/normus-kayler' }, { label: 'Sirius Kayler', to: '/personagens/sirius-kayler' }], curiosities: ['O brasão tradicional não representa uma coroa, mas um céu partido por três raios.'] }),
  record({ id: 'nimbus', name: 'Casa Nimbus', subtitle: 'Estrategistas da Serpente', summary: 'Linhagem de duelistas e planejadores, famosa por disciplina, ambição e leitura antecipada do campo de batalha.', description: 'Os Nimbus preferiam influenciar conflitos antes que começassem. Mantinham redes de informantes, estudavam logística e usavam magia para deslocamentos curtos e perturbação dos sentidos. Sua obsessão por controle gerou rivalidades internas. Registros oficiais os consideram extintos, mas arquivos incompletos impedem certeza.', category: 'Linhagem bruxa', status: 'Considerada extinta', lineage: 'Nimbus', origin: 'Leste de Avernor', traits: 'Cabelos brancos, olhos violetas, precisão e disciplina', motto: 'A vitória pertence a quem enxerga antes.', members: ['Registros suprimidos'], relations: [{ label: 'Era da Magia', to: '/historia/era-magia' }], curiosities: ['A serpente do brasão possui olhos abertos voltados para direções opostas.'] }),
  record({ id: 'rivs', name: 'Casa Rivs', subtitle: 'Guardiões das Águas', summary: 'A mais antiga linhagem conhecida, associada à água, neblina, gelo e preservação de conhecimento arcano.', description: 'Os Rivs ergueram arquivos em ilhas fluviais e aceitavam poucos visitantes. Sua magia era paciente: desviava correntes, ocultava travessias e conservava documentos contra umidade e fogo. Durante a Caça às Bruxas, os arquivos foram evacuados. O destino da família permanece desconhecido.', category: 'Linhagem bruxa', status: 'Destino desconhecido', lineage: 'Rivs', origin: 'Bacias do Mar Interior', traits: 'Cabelos brancos, olhos violetas, serenidade e memória ritual', motto: 'Toda verdade encontra seu caminho.', members: ['Último registro: Maelis Rivs'], relations: [{ label: 'Arquivo Submerso', to: '/lendas/arquivo-submerso' }], curiosities: ['Mapas Rivs marcam fontes de água antes de fronteiras políticas.'] }),
  record({ id: 'bellatrix', name: 'Casa Bellatrix', subtitle: 'A torre quebrada', summary: 'Família principesca rebelde que converteu uma fortaleza de fronteira em refúgio para perseguidos.', description: 'Os Bellatrix perderam terras ao recusar o recrutamento forçado de aldeões. Nas Montanhas Cinzentas, reorganizaram seus títulos: príncipe passou a significar guardião eleito da fortaleza, não proprietário do povo. Namídia herdou essa responsabilidade e abriu abrigo para Normus.', category: 'Casa rebelde', status: 'Ativa', lineage: 'Bellatrix', kingdom: 'Montanhas Cinzentas', origin: 'Fortaleza do Véu', traits: 'Austeridade, hospitalidade juramentada e resistência a cercos', motto: 'Do que foi quebrado faremos abrigo.', members: ['Namídia Bellatrix', 'Marek Bellatrix'], relations: [{ label: 'Namídia Bellatrix', to: '/personagens/namidia-bellatrix' }, { label: 'Fortaleza do Véu', to: '/cidades/fortaleza-do-veu' }] }),
  record({ id: 'arden', name: 'Casa Arden', subtitle: 'Guardiões dos celeiros', summary: 'Família nobre de Valoria dividida entre a corte e os compromissos assumidos com comunidades rurais.', description: 'A riqueza Arden vem de diques, moinhos e armazéns, não de minas. Após uma fome, a casa aceitou limites públicos ao preço dos grãos. Ilyra Arden, herdeira e capitã, tenta preservar esse pacto enquanto parentes pressionam por expansão territorial.', category: 'Casa nobre', status: 'Ativa', lineage: 'Arden', kingdom: 'Valoria', origin: 'Valóris', traits: 'Administração rural, cavalaria leve e negociação', motto: 'Primeiro a colheita, depois a coroa.', members: ['Ilyra Arden'], relations: [{ label: 'Ilyra Arden', to: '/personagens/ilyra-arden' }, { label: 'Valoria', to: '/reinos/valoria' }] }),
]

const houseEnrichment = {
  kayler: { genealogyId: 'kayler', inheritance: ['Dom de tempestade transmitido pelo sangue', 'Sinais frequentes: cabelo branco e olhos violetas', 'Manifestação pode permanecer silenciosa por gerações'], vows: ['Corrente Celeste', 'Juramento Arcano contra governo dos povos'], survival: ['Normus deixou artefatos e pacto', 'Sirius é o último membro conhecido, não uma prova de extinção total'], rivalries: ['Coroas que buscavam domínio', 'Divergências filosóficas com o controle Nimbus'] },
  nimbus: { genealogyId: 'nimbus', inheritance: ['Magia de vontade, percepção e deslocamento', 'Olhos violetas e cabelo branco como sinais recorrentes', 'Expressão do dom varia com disciplina e medo'], vows: ['Corrente Escarlate', 'Proteção sem soberania'], survival: ['A casa escolheu combate aberto durante a perseguição', 'Registros oficiais declaram extinção, mas não comprovam todos os ramos'], rivalries: ['Conflitos internos por controle', 'Conselho dos Sete Reis'] },
  rivs: { genealogyId: 'rivs', inheritance: ['Afinidade com água, neblina, gelo e memória', 'Sinais físicos compartilhados pelas três Casas', 'Possível herança recessiva não confirmada'], vows: ['Corrente Profunda', 'Conhecimento deve continuar sem possuir quem o guarda'], survival: ['Bibliotecas evacuadas', 'Ramos e arquivos desapareceram juntos'], rivalries: ['Coroas interessadas nos arquivos', 'Necromantes em busca de memória preservada'] },
  bellatrix: { genealogyId: 'bellatrix', inheritance: ['Não possui magia hereditária', 'Título de guardião depende de eleição e serviço'], vows: ['A Chama sem Coroa', 'Abrigo acima de trono'], survival: ['Cifras de inventário esconderam descendentes', 'Fortaleza do Véu preserva ramos públicos'], rivalries: ['Coroas expansionistas', 'Fortalezas que rejeitam coordenação'] },
  arden: { genealogyId: 'valoria', inheritance: ['Terras e deveres de dique', 'Sucessão limitada pelas Sete Pontes'], vows: ['Primeiro a colheita, depois a coroa'], survival: ['Poder econômico distribuído por moinhos e armazéns'], rivalries: ['Ala cortesã contra pactos agrários', 'Ilyra contra parentes expansionistas'] },
}

export const houses = houseRecords.map((house) => {
  const dossier = houseDossiers[house.id]
  const { additionalRelations = [], ...details } = dossier
  return { ...house, ...houseEnrichment[house.id], ...details, relations: [...house.relations, ...additionalRelations] }
})
