import { record } from '../schema.js'
import { kingdomDossiers } from '../places/dossiers.js'

const kingdomRecords = [
  record({ id: 'winterfeld', name: 'Winterfeld', subtitle: 'Gelo, muralhas e juramentos antigos', summary: 'Reino setentrional protegido por montanhas, gigantes aliados e pela presença rara do dragão branco Vyrasul.', description: 'Winterfeld vive de mineração profunda, criação de cervos-das-neves e pedágios nas passagens glaciais. Seu conselho de jarls limita a autoridade da coroa, sobretudo durante invernos de fome. Vyrasul não pertence ao reino nem obedece ao monarca: o dragão natural escolheu permanecer nas geleiras após ter sido salvo de caçadores.', image: '/assets/images/kingdoms/kingdom-winterfeld-page.webp', thumbnail: '/assets/images/kingdoms/kingdom-winterfeld-card.webp', category: 'Reino humano', status: 'Soberano', location: 'Extremo norte', capital: 'Winterheim', symbol: 'Lobo branco sob uma estrela de gelo', government: 'Monarquia pactuada com o Conselho dos Jarls', economy: 'Ferro glacial, peles, sal e controle das passagens', relations: [{ label: 'Vyrasul', to: '/criaturas/vyrasul' }, { label: 'Winterheim', to: '/cidades/winterheim' }], events: ['Pacto dos Gigantes', 'Cerco do Degelo'], curiosities: ['As muralhas mantêm depósitos públicos de grãos para três invernos.'], quotes: ['No norte, uma promessa vale o peso do abrigo.'] }),
  record({ id: 'sylvaris', name: 'Sylvaris', subtitle: 'O coração vivo da Floresta Antiga', summary: 'Reino élfico protegido por árvores milenares, sentinelas e caminhos que se transformam sob orientação dos guardiões.', description: 'Sylvaris não separa cidade e floresta: pontes crescem entre troncos, a água define bairros e construções novas exigem o consentimento de círculos de guardiões. A Rainha governa com um conselho de memórias, formado por representantes de ofícios e bosques. A amizade com Normus garantiu refúgio aos Kayler e originou um pacto secreto sobre seus descendentes.', image: '/assets/images/kingdoms/kingdom-sylvaris-page.webp', thumbnail: '/assets/images/kingdoms/kingdom-sylvaris-card.webp', category: 'Reino élfico', status: 'Soberano', location: 'Oeste e sudoeste', capital: 'Lethariel', symbol: 'Folha de prata sobre esmeralda', government: 'Monarquia aconselhada pelos Círculos da Memória', economy: 'Medicina, madeira caída, vidro vegetal e manuscritos', relations: [{ label: 'Elara', to: '/personagens/elara' }, { label: 'Rainha Aelwen', to: '/personagens/rainha-aelwen' }, { label: 'Lethariel', to: '/cidades/lethariel' }], events: ['Defesa de Sylvaris', 'Pacto dos Descendentes'], curiosities: ['Cortar uma árvore viva sem autorização é tratado como agressão política.'], quotes: ['A floresta não fecha caminhos; ela decide quem está preparado para atravessá-los.'] }),
  record({ id: 'kar-dum', name: 'Kar-Dûm', subtitle: 'Pedra, fogo e memória', summary: 'Confederação anã de salões subterrâneos, minas profundas e forjas cujo acesso depende de juramentos comerciais.', description: 'Kar-Dûm é uma união de salões, não uma coroa simples. Mestres de forja, cartógrafos de túneis e guardiões de aquíferos dividem o poder. A riqueza mineral sustenta o reino, mas também o força a negociar alimentos com Valoria. Cada túnel abandonado é lacrado com uma placa explicando a razão — desabamento, gás, criatura ou dívida.', image: '/assets/images/kingdoms/kingdom-kar-dum-page.webp', thumbnail: '/assets/images/kingdoms/kingdom-kar-dum-card.webp', category: 'Reino anão', status: 'Confederação soberana', location: 'Cordilheira central', capital: 'Thur-Kar', symbol: 'Martelo dourado sobre montanha negra', government: 'Conselho dos Nove Salões', economy: 'Aço, ferramentas, engenharia hidráulica e gemas', relations: [{ label: 'Thur-Kar', to: '/cidades/thur-kar' }, { label: 'Martelo de Orun', to: '/artefatos/martelo-de-orun' }], events: ['Abertura dos Portões', 'Guerra dos Túneis Vazios'], curiosities: ['Contratos são gravados em lâminas finas de ardósia.'], quotes: ['Pedra registra até o golpe que não a partiu.'] }),
  record({ id: 'valoria', name: 'Valoria', subtitle: 'Campos dourados e poder mercantil', summary: 'A planície fértil que alimenta boa parte do continente converteu trigo, cavalaria e crédito em influência política.', description: 'Valoria cresceu ao controlar rios navegáveis e celeiros. Grandes famílias rurais competem com corporações urbanas, produzindo uma corte rica e instável. A coroa consegue financiar guerras alheias, mas depende de camponeses que já interromperam colheitas para exigir preços mínimos e reparos nos diques.', image: '/assets/images/kingdoms/kingdom-valoria-page.webp', thumbnail: '/assets/images/kingdoms/kingdom-valoria-card.webp', category: 'Reino humano', status: 'Soberano', location: 'Planícies centrais', capital: 'Valóris', symbol: 'Leão dourado em campo vermelho', government: 'Monarquia de pactos agrários', economy: 'Grãos, cavalos, crédito e transporte fluvial', relations: [{ label: 'Valóris', to: '/cidades/valoris' }, { label: 'Casa Arden', to: '/casas/arden' }], events: ['Revolta dos Celeiros', 'Pacto das Sete Pontes'], curiosities: ['A moeda valoriana é aceita nos portos de Eldemar, mas sofre deságio no norte.'], quotes: ['Quem controla o pão não precisa levantar a espada primeiro.'] }),
  record({ id: 'ravenhold', name: 'Ravenhold', subtitle: 'A coroa da guerra', summary: 'Reino de legiões disciplinadas e fortalezas austeras, dividido entre veteranos reformistas e uma aristocracia expansionista.', description: 'As fronteiras abertas de Ravenhold favoreceram uma cultura de fortificações e serviço militar. A eficiência de suas estradas contrasta com a vigilância nas cidades. Depois da Caça às Bruxas, oficiais mais jovens passaram a questionar os decretos que seus predecessores executaram, tornando o exército o principal palco político do reino.', image: '/assets/images/kingdoms/kingdom-ravenhold-page.webp', thumbnail: '/assets/images/kingdoms/kingdom-ravenhold-card.webp', category: 'Reino humano', status: 'Soberano', location: 'Leste central', capital: 'Ravencastle', symbol: 'Corvo negro sobre aço', government: 'Monarquia militar com Senado de Estandartes', economy: 'Armas, pedágios terrestres, cavalos e mercenários', relations: [{ label: 'Ravencastle', to: '/cidades/ravencastle' }, { label: 'Guerra da Cinza Branca', to: '/guerras/guerra-da-cinza-branca' }], events: ['Reforma das Legiões', 'Guerra da Cinza Branca'], curiosities: ['Todo marco de estrada indica também a distância até o abrigo militar mais próximo.'], quotes: ['Disciplina sem consciência é apenas obediência bem vestida.'] }),
  record({ id: 'eldemar', name: 'Eldemar', subtitle: 'Senhores das marés', summary: 'Potência marítima que equilibra estaleiros, guildas de navegadores e rotas perigosas pelo Arquipélago das Brumas.', description: 'Eldemar é governado a partir de um porto construído sobre ilhas ligadas por pontes móveis. Sua frota protege comboios, cobra licenças e, em segredo, negocia informações com contrabandistas. A dependência de madeira de Sylvaris criou protocolos rígidos: apenas troncos caídos e marcados podem entrar nos estaleiros reais.', image: '/assets/images/kingdoms/kingdom-eldemar-page.webp', thumbnail: '/assets/images/kingdoms/kingdom-eldemar-card.webp', category: 'Reino humano', status: 'Soberano', location: 'Costa sul', capital: 'Porto de Eldemar', symbol: 'Tridente de prata sobre azul profundo', government: 'Monarquia marítima e Conselho das Marés', economy: 'Navegação, sal, pesca, mapas e construção naval', relations: [{ label: 'Porto de Eldemar', to: '/cidades/porto-de-eldemar' }, { label: 'Kraken de Eldemar', to: '/criaturas/kraken-de-eldemar' }], events: ['Batalha das Águas Negras', 'Tratado da Madeira Caída'], curiosities: ['Cartas náuticas oficiais omitem enseadas usadas em rotas de evacuação.'], quotes: ['Nenhuma muralha é tão larga quanto o mar.'] }),
  record({ id: 'montanhas-cinzentas', name: 'Montanhas Cinzentas', subtitle: 'Refúgio dos que não possuem reino', summary: 'Território confederado de exilados, desertores e famílias perseguidas, onde Normus conheceu Namídia Bellatrix.', description: 'A região não possui rei nem capital permanente. Fortalezas independentes elegem uma Mesa de Vigias durante crises e voltam à autonomia quando o perigo passa. O clima severo limita lavouras, tornando cabras, cogumelos de caverna e pedágios de passagem essenciais. A Fortaleza do Véu, antiga casa de Namídia, é um reduto de reunião e protege arquivos sobre fugitivos da Caça às Bruxas, sem governar as demais fortalezas.', image: '/assets/images/kingdoms/kingdom-montanhas-cinzentas-page.webp', thumbnail: '/assets/images/kingdoms/kingdom-montanhas-cinzentas-card.webp', category: 'Território rebelde', status: 'Confederação autônoma', location: 'Nordeste montanhoso', capital: 'Sem capital permanente', principalStronghold: 'Fortaleza do Véu', symbol: 'Torre quebrada diante de três picos', government: 'Confederação temporária de fortalezas', economy: 'Criação de cabras, minério pobre, escolta e pedágios', relations: [{ label: 'Namídia Bellatrix', to: '/personagens/namidia-bellatrix' }, { label: 'Fortaleza do Véu', to: '/cidades/fortaleza-do-veu' }], events: ['Cerco da Fortaleza do Véu', 'Refúgio de Normus Kayler'], curiosities: ['A ausência de capital formal é uma defesa contra conquista e corrupção.'], quotes: ['Quem perdeu uma pátria aprende a construir abrigo.'] }),
]

const kingdomEnrichment = {
  winterfeld: {
    demographics: ['Humanos concentrados em vales termais', 'Comunidades de gigantes mantêm autonomia nos passos', 'Migração sazonal acompanha rebanhos e minas'],
    laws: ['Abrigo de emergência não pode ser recusado', 'Estoques públicos são auditados antes do inverno', 'Conselho dos Jarls confirma a sucessão'],
    military: ['Infantaria de passagem', 'Batedores de gelo', 'Vyrasul não integra as forças do reino'],
    internalConflicts: ['Jarls de mineração contra guardiões de aquíferos', 'Culto indevido a Vyrasul rejeitado pela Vigília da Última Brasa'],
    dailyLife: ['Banhos termais públicos', 'Conservação de alimento', 'Reparo coletivo de telhados antes das quarenta noites'],
  },
  sylvaris: {
    demographics: ['Elfos em cidades-jardim e comunidades de bosque', 'Estrangeiros concentrados em Porto Verde', 'Refugiados históricos protegidos por nomes cifrados'],
    laws: ['Cortar árvore viva exige consentimento dos Círculos', 'A coroa não pode vender território', 'Sucessão é escolha entre descendentes elegíveis'],
    military: ['Sentinelas florestais', 'Arqueiros de plataformas', 'Caminhos recolhidos funcionam como defesa, não magia'],
    internalConflicts: ['Sigilo do pacto Kayler', 'Debate entre isolamento e responsabilidade continental', 'Receio sobre a escolha de Elara'],
    dailyLife: ['Manejo por estação', 'Jardins memoriais', 'Ofícios representados nos Círculos da Memória'],
  },
  'kar-dum': {
    demographics: ['Anões organizados por salão, sangue e ofício', 'Mercadores de superfície nos portões externos', 'Bairros definidos por água e ventilação'],
    laws: ['Toda escavação responde aos Nove Ecos', 'Três salões aprovam abertura ancestral', 'Adoção de ofício não falsifica descendência de sangue'],
    military: ['Guardiões de túnel', 'Engenheiros de evacuação', 'Escudos adaptados a corredores'],
    internalConflicts: ['Tradição contra o Oitavo Golpe da inovação', 'Forjas contra guardiões de água', 'Dependência alimentar de Valoria'],
    dailyLife: ['Turnos regulados por sinos de ventilação', 'Contratos em ardósia', 'Ferramentas nomeadas e herdadas'],
  },
  valoria: {
    demographics: ['Maioria rural junto a diques e canais', 'Guildas de barqueiros nas cidades', 'Nobreza de celeiro e crédito'],
    laws: ['Preço de emergência para grãos', 'Sete Pontes confirmam a sucessão', 'Diques privados devem servir à drenagem pública'],
    military: ['Cavalaria leve', 'Guardas fluviais', 'Levas rurais politicamente contestadas'],
    internalConflicts: ['Ala expansionista contra pactos agrários', 'Corte contra associações rurais', 'Popularidade de Ilyra ameaça parentes'],
    dailyLife: ['Mercados de peso público', 'Festivais de abertura dos canais', 'Mutirões de dique'],
  },
  ravenhold: {
    demographics: ['Famílias militares nos anéis internos', 'Artesãos de armas e carroças', 'Veteranos reformistas em bairros periféricos'],
    laws: ['Serviço militar sujeito a registro civil', 'Senado confirma herdeiros', 'Direito à recusa de ordem criminosa ainda em disputa'],
    military: ['Legiões permanentes', 'Estradas e abrigos logísticos', 'Senado de Estandartes'],
    internalConflicts: ['Reformistas contra defensores da Caça às Bruxas', 'Vigilância urbana', 'Pretensão de Cassor Corven'],
    dailyLife: ['Bairros em antigos anéis defensivos', 'Treino cívico de incêndio', 'Mercados sob inspeção militar'],
  },
  eldemar: {
    demographics: ['Marinheiros e famílias portuárias', 'Guildas de pilotos do arquipélago', 'Comunidades de maré nos níveis baixos'],
    laws: ['Licença de navegação condiciona sucessão', 'Madeira de Sylvaris precisa de marca de queda', 'Sinos portuários têm código público'],
    military: ['Frota de escolta', 'Pilotos de águas rasas', 'Pontes móveis de defesa'],
    internalConflicts: ['Conselho das Marés contra a coroa', 'Reparações das Águas Negras', 'Relação ambígua com contrabandistas'],
    dailyLife: ['Turnos marcados por maré', 'Casas nos terraços altos', 'Juramentos em placas de cera'],
  },
  'montanhas-cinzentas': {
    demographics: ['Famílias exiladas de diversas origens', 'Pastores, mineiros e escoltas', 'Fortalezas com cidadania por serviço'],
    laws: ['Mesa de Vigias existe apenas durante crises', 'Títulos são dever temporário', 'Abrigar perseguido pode superar tratado externo'],
    military: ['Vigias de passagem', 'Defesa de cerco', 'Rotas cifradas de evacuação'],
    internalConflicts: ['Autonomia contra necessidade de coordenação', 'Segredos Bellatrix', 'Pedágios entre fortalezas'],
    dailyLife: ['Criação de cabras', 'Cogumelos de caverna', 'Inventários usados também como memória de refugiados'],
  },
}

export const kingdoms = kingdomRecords.map((kingdom) => ({ ...kingdom, ...kingdomEnrichment[kingdom.id], ...kingdomDossiers[kingdom.id] }))
