import { record } from '../schema.js'
import { relicDossiers } from '../items/dossiers.js'
import { applyArchiveDossiers, relicArchiveDossiers } from '../editorial/archiveDossiers.js'

const relicRecords = [
  record({ id: 'medalhao-ultimo-sussurro', name: 'Medalhão do Último Sussurro', subtitle: 'A morte paga com memória', summary: 'Relíquia capaz de alcançar o último eco de um morto ao custo de lembranças pessoais de quem pergunta.', description: 'Cada uso apaga uma memória ligada emocionalmente à pergunta. Respostas vêm como sensação e fragmento, nunca como testemunho completo. Necromantes procuram o objeto por confundir acesso com autoridade.', category: 'Relíquia do Véu Partido', status: 'Perdida', truthStatus: 'witnessed', limitations: ['Cobra memória pessoal', 'Respostas fragmentárias', 'Atrai Retornados'], relations: [{ label: 'Necromancia', to: '/necromancia/necromancia' }] }),
  record({ id: 'fulgarion', name: 'Fulgarion', subtitle: 'A Espada dos Sete Trovões', summary: 'Espada de Normus e Sirius, condutora do legado Kayler e uma das Cinco Relíquias.', description: 'Suas manifestações conhecidas recebem os nomes Despertar, Passo Celeste, Corrente Partida, Céu Descendente, Tempestade Interior, Julgamento Violeta e Porta da Tempestade. Cada etapa exige maior controle, mana e responsabilidade; a lâmina não cria o dom em um portador sem sangue Kayler. O efeito integral da sétima manifestação não faz parte do registro público.', category: 'Relíquia do Véu Partido', status: 'Com Sirius', origin: 'Normus Kayler', truthStatus: 'documented', abilities: ['Despertar', 'Passo Celeste', 'Corrente Partida', 'Céu Descendente', 'Tempestade Interior', 'Julgamento Violeta', 'Porta da Tempestade — efeito integral não publicado'], limitations: ['Sobrecarga nervosa', 'Dependência do dom Kayler', 'Limite final não registrado publicamente'], relations: [{ label: 'Sirius Kayler', to: '/personagens/sirius-kayler' }, { label: 'Espada da Trovoada', to: '/artefatos/espada-da-trovoada' }] }),
  record({ id: 'aelysar', name: 'Aelysar', subtitle: 'O Arco da Primeira Raiz', summary: 'Arco destinado a Elara quando assumir o trono de Sylvaris, com seis flechas ligadas a responsabilidades da coroa.', description: 'As flechas são Raiz, Lua Verde, Memória, Caminho, Copa Silenciosa e Último Ramo. Cada uma é única e retorna apenas quando a obrigação representada foi cumprida. Aelysar não concede magia de sangue; responde a pactos rúnicos, ao reino e à portadora reconhecida.', category: 'Relíquia do Véu Partido', status: 'Guardada até a sucessão', origin: 'Sylvaris', truthStatus: 'redacted', abilities: ['Flecha da Raiz', 'Lua Verde', 'Memória', 'Caminho', 'Copa Silenciosa', 'Último Ramo'], relations: [{ label: 'Elara', to: '/personagens/elara' }, { label: 'Sucessão de Sylvaris', to: '/sucessoes/sylvaris' }] }),
  record({ id: 'varkhael-seryn', name: 'Varkhael e Seryn', subtitle: 'As Lâminas da Dor Incendiária', summary: 'Espadas gêmeas: Varkhael alimenta-se da fúria; Seryn, da dor; ambas podem queimar nomes e memórias.', description: 'As lâminas tornam emoções em calor, mas não distinguem justiça de obsessão. Usadas juntas, podem apagar o nome de uma pessoa dos registros e das lembranças próximas. Separadas, procuram portadores em extremos emocionais.', category: 'Relíquia do Véu Partido', status: 'Separadas', truthStatus: 'legendary', limitations: ['Amplificam emoção', 'Queimam memória', 'O uso conjunto ameaça identidade coletiva'], relations: [{ label: 'Corte de Cinza', to: '/faccoes/corte-de-cinza' }] }),
  record({ id: 'ishara', name: 'Ishara', subtitle: 'O Véu da Última Cura', summary: 'Tecido capaz de curar ao transferir dor, reduzir vida ou armazenar sofrimento no próprio material.', description: 'Ishara não elimina preço: decide quem o carrega e quando. Dores absorvidas permanecem como bordados escuros e podem ser libertadas de uma vez. Curadores discutem se usar o objeto sem consentimento é salvação ou violência.', category: 'Relíquia do Véu Partido', status: 'Localização desconhecida', truthStatus: 'witnessed', limitations: ['Transfere dor', 'Pode reduzir vida', 'Acumula sofrimento', 'Exige consentimento ético'], relations: [{ label: 'Profecia das Cinco Relíquias', to: '/profecias/cinco-reliquias' }] }),
]

export const relics = applyArchiveDossiers(relicRecords.map((relic) => ({ ...relic, ...relicDossiers[relic.id] })), relicArchiveDossiers)
