import { record } from '../schema.js'

export const creatures = [
  record({ id: 'vyrasul', name: 'Vyrasul', subtitle: 'O dragão branco de Winterfeld', summary: 'Um dos três únicos dragões conhecidos, criatura natural que escolheu permanecer nas geleiras de Winterfeld.', description: 'Vyrasul não governa, não recebe tributos e não responde à coroa. O dragão foi encontrado ferido por gigantes do norte e sobreviveu graças a uma trégua entre caçadores e curadores. Desde então, ataca grandes ameaças próximas às geleiras, mas ignora conflitos políticos. Seu sopro retira calor rapidamente; usá-lo por longos períodos o deixa vulnerável.', category: 'Dragão', status: 'Vivo — avistado', origin: 'Desconhecida', location: 'Geleiras de Winterfeld', race: 'Dragão', threat: 'Lendária', habitat: 'Geleiras e picos', relations: [{ label: 'Winterfeld', to: '/reinos/winterfeld' }], curiosities: ['Marcas de voo sugerem que evita assentamentos durante migrações de animais.'] }),
  record({ id: 'alcarion', name: 'Alcarion', subtitle: 'O dragão das marés ausentes', summary: 'Segundo dos três dragões conhecidos; desapareceu sobre o Mar das Estrelas há mais de um século.', description: 'Relatos descrevem escamas escuras com brilho esverdeado e hábitos costeiros. Alcarion alimentava-se de grandes peixes e descansava em ilhas sem população. Seu desaparecimento coincide com uma anomalia marítima, mas não há evidência de morte ou cativeiro.', category: 'Dragão', status: 'Desaparecido', origin: 'Arquipélago das Brumas', location: 'Último registro: Mar das Estrelas', race: 'Dragão', threat: 'Lendária', habitat: 'Ilhas e mar aberto', relations: [{ label: 'Eldemar', to: '/reinos/eldemar' }], curiosities: ['Nenhum ovo de dragão foi autenticado por estudiosos.'] }),
  record({ id: 'mhazir', name: 'Mhazir', subtitle: 'O dragão de cobre', summary: 'Terceiro dragão conhecido, desaparecido após cruzar as Montanhas Cinzentas durante a Caça às Bruxas.', description: 'Mhazir possuía escamas de cobre fosco e caçava grandes herbívoros nas terras áridas. Uma cicatriz na asa direita tornava seu voo reconhecível. A última rota registrada segue para além do limite cartografado; teorias que o colocam à frente de um império são rejeitadas por falta de evidência e por contradizerem o comportamento natural dos dragões.', category: 'Dragão', status: 'Desaparecido', origin: 'Deserto de Zharak', location: 'Último registro: Montanhas Cinzentas', race: 'Dragão', threat: 'Lendária', habitat: 'Desertos e planaltos', relations: [{ label: 'Montanhas Cinzentas', to: '/reinos/montanhas-cinzentas' }], curiosities: ['Fragmentos atribuídos às suas escamas eram minério de cobre comum.'] }),
  record({ id: 'grifo-das-alturas', name: 'Grifo das Alturas', subtitle: 'Sentinela dos penhascos', summary: 'Predador alado territorial das montanhas, admirado por cavaleiros e temido por criadores de cabras.', description: 'Grifos formam pares sazonais e defendem ninhos em paredões inacessíveis. Não aceitam montaria; histórias de cavaleiros de grifo são alegorias militares. Sinos agudos e rebanhos cobertos reduzem ataques sem exigir extermínio.', category: 'Fera alada', status: 'Estável', location: 'Cordilheiras de Avernor', race: 'Fera', threat: 'Alta', habitat: 'Penhascos e montanhas', relations: [{ label: 'Winterfeld', to: '/reinos/winterfeld' }] }),
  record({ id: 'hidra-dos-pantanos', name: 'Hidra dos Pântanos', subtitle: 'A fome que se divide', summary: 'Réptil de múltiplos pescoços cuja regeneração torna combates prolongados quase impossíveis.', description: 'A hidra não cria cabeças infinitas: cada perda consome reservas corporais e exige alimento abundante. Caçadores experientes evitam feri-la e preferem conduzi-la para áreas sem presas. Fogo descontrolado é perigoso, pois pântanos secos podem queimar por meses.', category: 'Fera lacustre', status: 'Rara', location: 'Pântanos meridionais', race: 'Fera', threat: 'Extrema', habitat: 'Pântanos e lagos rasos', relations: [{ label: 'Mar Interior', to: '/locais/mar-interior' }] }),
  record({ id: 'kraken-de-eldemar', name: 'Kraken de Eldemar', subtitle: 'O peso sob as rotas', summary: 'Cefalópode colossal registrado em águas profundas, responsável por mudanças sazonais nas rotas mercantes.', description: 'O nome singular esconde a incerteza: estudiosos não sabem se os avistamentos pertencem ao mesmo animal. A criatura parece seguir correntes frias e cardumes. Navios que desligam sinos de casco e evitam despejar vísceras reduzem encontros.', category: 'Fera marinha', status: 'Avistamentos esporádicos', location: 'Mar das Estrelas', race: 'Fera', threat: 'Lendária', habitat: 'Mar profundo', relations: [{ label: 'Eldemar', to: '/reinos/eldemar' }] }),
  record({ id: 'cervo-do-nevoeiro', name: 'Cervo do Nevoeiro', subtitle: 'Guia das clareiras', summary: 'Grande herbívoro da Floresta Antiga cuja pelagem reflete tons do ambiente úmido.', description: 'A capacidade de parecer desaparecer vem de pelos translúcidos, silêncio e conhecimento das trilhas, não de teletransporte. Elfos observam seus deslocamentos para prever fungos tóxicos e alterações na água.', category: 'Fauna antiga', status: 'Protegido', location: 'Floresta Antiga', race: 'Animal', threat: 'Baixa', habitat: 'Bosques úmidos', relations: [{ label: 'Sylvaris', to: '/reinos/sylvaris' }] }),
  record({ id: 'lobo-de-vidro', name: 'Lobo de Vidro', subtitle: 'Caçador das salinas', summary: 'Canídeo de pelos rígidos cobertos por sais minerais, adaptado às noites frias das terras áridas.', description: 'Os pelos tilintam quando o animal corre, razão pela qual caça contra o vento. Bandos evitam fogo e assentamentos grandes, mas seguem caravanas debilitadas. A remoção dos depósitos minerais causa feridas e é proibida por caçadores responsáveis.', category: 'Predador terrestre', status: 'Estável', location: 'Deserto de Zharak', race: 'Animal', threat: 'Moderada', habitat: 'Salinas e desertos', relations: [{ label: 'Deserto de Zharak', to: '/locais/deserto-de-zharak' }] }),
  record({ id: 'vigia-de-pedra', name: 'Vigia de Pedra', subtitle: 'Colônia das cavernas profundas', summary: 'Organismo colonial mineralizado que reage a vibrações e é frequentemente confundido com estátua.', description: 'Cada “vigia” é formado por milhares de pequenos seres que depositam uma carapaça comum. Vibrações violentas provocam o fechamento súbito da colônia, capaz de bloquear túneis. Mineiros anões usam batidas ritmadas para anunciar passagem.', category: 'Organismo colonial', status: 'Raro', location: 'Kar-Dûm', race: 'Fauna subterrânea', threat: 'Moderada', habitat: 'Cavernas minerais', relations: [{ label: 'Kar-Dûm', to: '/reinos/kar-dum' }] }),
]
