import { record } from '../schema.js'
import { characterDossiers } from './dossiers.js'

const characterRecords = [
  record({
    id: 'sirius-kayler', name: 'Sirius Kayler', subtitle: 'O último bruxo conhecido',
    summary: 'Filho de Normus Kayler e Namídia Bellatrix, herdeiro de uma linhagem perseguida e de um pacto secreto com Sylvaris.',
    description: 'Sirius nasceu escondido na Floresta Antiga durante os últimos anos da Caça às Bruxas. Herdou a magia de tempestade dos Kayler, mas cresceu sem conhecer a extensão do preço pago por seus pais. Apesar da idade extraordinária, conserva aparência jovem. O domínio de seus poderes depende de controle emocional: descargas intensas ferem nervos, atraem atenção e podem incendiar o ambiente que tenta proteger.',
    image: '/assets/images/characters/sirius-kayler-page.webp', thumbnail: '/assets/images/characters/sirius-kayler-card.webp', gallery: ['/assets/images/locations/jornada-floresta-antiga-banner.webp'], accent: '#9d7ad1', thumbnailPosition: 'center 18%', heroPosition: '58% 18%',
    category: 'Protagonista', status: 'Vivo', origin: 'Floresta Antiga', location: 'Em jornada', period: 'Era atual — 1204 d.C.', race: 'Humano — linhagem bruxa', lineage: 'Kayler', age: 'cerca de 500 anos; aparência de 20', genealogyId: 'kayler',
    appearance: 'Pele morena; cabelos longos, brancos e trançados; olhos violetas; cicatrizes no rosto; bigode escuro; alto e musculoso; aparência jovem.',
    objectives: ['Descobrir o que Normus ocultou sem entregar sua autonomia às coroas', 'Proteger possíveis sobreviventes Nimbus e Rivs', 'Compreender o pacto com Sylvaris antes de aceitá-lo ou recusá-lo'],
    fears: ['Tornar-se uma arma de Estado', 'Ferir inocentes durante uma sobrecarga', 'Descobrir que sua sobrevivência custou mais vidas do que consegue suportar'],
    flaws: ['Isolamento prolongado tornou confiança e negociação difíceis', 'Confunde autocontrole com silêncio emocional', 'Pode responder à manipulação tentando resolver tudo sozinho'],
    beliefs: ['Poder não concede direito de governo', 'Memória sem escolha pode tornar-se outra prisão'],
    equipment: ['Fulgarion, a espada herdada de Normus', 'Carta cifrada', 'Medalhão do pacto de Sylvaris', 'Armadura original de influência oriental; depois, manto negro com capuz'],
    timeline: ['704 d.C. — nascimento secreto', '704 d.C. — morte de Namídia e batalha final de Normus', '1204 d.C. — recebimento da herança e saída do isolamento'],
    abilities: ['Magia hereditária de tempestade', 'Condução de raios pela espada', 'Combate de curta distância', 'Resistência arcana acima do comum'],
    disputedAbilities: ['Relatos tardios atribuem a Sirius uma forma de corvo; nenhuma testemunha identificada ou registro material confirmou a metamorfose.'],
    limitations: ['Sobrecarga provoca tremores e perda de sensibilidade', 'Não cria tempestades sem umidade atmosférica', 'É reconhecível pelos traços da linhagem'],
    relations: [{ label: 'Normus Kayler — pai', to: '/personagens/normus-kayler' }, { label: 'Namídia Bellatrix — mãe', to: '/personagens/namidia-bellatrix' }, { label: 'Elara — aliada ligada ao pacto', to: '/personagens/elara' }, { label: 'Genealogia Kayler', to: '/personagens/sirius-kayler/genealogia' }, { label: 'Casa Kayler', to: '/casas/kayler' }, { label: 'Fulgarion', to: '/reliquias/fulgarion' }, { label: 'Caça às Bruxas', to: '/historia/caca-bruxas' }],
    events: ['Nascimento secreto na Floresta Antiga', 'Recebimento da herança de Normus', 'Encontro com Elara'],
    curiosities: ['Carrega uma carta de Normus que ainda não revelou a terceiros.', 'Evita usar magia perto de crianças por medo de perder o controle.'],
    quotes: ['Sobreviver não torna ninguém inteiro. Apenas oferece tempo para escolher o que fazer com as partes.'],
  }),
  record({
    id: 'normus-kayler', name: 'Normus Kayler', subtitle: 'O Bruxo mais poderoso de Avernor',
    summary: 'Bruxo da Casa Kayler, mestre das tempestades, Cavaleiro de Honra de Sylvaris e pai de Sirius.',
    description: 'Normus foi a força arcana mais poderosa registrada em Avernor. Não era um guerreiro humano que aprendera feitiços, mas um bruxo hereditário cuja disciplina transformava tempestades em defesa precisa. Recusou coroas e serviu comunidades ameaçadas. A Rainha de Sylvaris foi sua grande amiga e aliada — nunca amante. Entre ambos existiu um pacto secreto relacionado aos descendentes de suas casas.',
    image: '/assets/images/characters/normus-kayler-v2-page.webp', thumbnail: '/assets/images/characters/normus-kayler-v2-card.webp', accent: '#8974ba', thumbnailPosition: 'center 16%', heroPosition: '61% 17%',
    category: 'Figura histórica', status: 'Morto — lendário', origin: 'Casa Kayler', location: 'Último registro: Floresta Antiga', period: 'Era das Coroas / Caça às Bruxas', race: 'Humano — linhagem bruxa', lineage: 'Kayler', genealogyId: 'kayler',
    appearance: 'Pele morena; cabelos longos, brancos e grisalhos; olhos violetas; fisionomia de aproximadamente quarenta anos; cicatrizes antigas; presença austera e sinais de décadas de magia.',
    objectives: ['Impedir que coroas convertessem bruxos em soberanos ou armas', 'Preservar Sirius como pessoa livre', 'Manter abertas rotas civis durante as guerras'],
    fears: ['Que o próprio prestígio anulasse o Juramento Arcano', 'Que Sirius herdasse apenas inimigos e não escolhas'],
    flaws: ['Assumiu responsabilidades que deveriam ter sido distribuídas', 'Escondeu verdades de aliados para protegê-los, reduzindo sua capacidade de consentir'],
    beliefs: ['“Nenhum sangue tocado pelo Primeiro Céu deverá sentar-se acima dos povos.”', 'A Rainha de Sylvaris era amiga e aliada'],
    equipment: ['Fulgarion', 'Armadura de campanha reparada em Kar-Dûm', 'Medalhão da Folha Partida'],
    abilities: ['Domínio arcano superior', 'Condução e dispersão de tempestades', 'Barreiras elétricas', 'Leitura de campos mágicos'],
    limitations: ['A escala de seus feitos exigia recuperação prolongada', 'Recusava magia que sacrificasse inocentes', 'O vínculo com tempestades não anulava leis naturais'],
    relations: [{ label: 'Sirius Kayler — filho', to: '/personagens/sirius-kayler' }, { label: 'Namídia Bellatrix — companheira', to: '/personagens/namidia-bellatrix' }, { label: 'Rainha Aelwen — amiga e aliada', to: '/personagens/rainha-aelwen' }, { label: 'Casa Kayler', to: '/casas/kayler' }, { label: 'Sylvaris', to: '/reinos/sylvaris' }, { label: 'Fulgarion', to: '/artefatos/espada-da-trovoada' }, { label: 'Caça às Bruxas', to: '/historia/caca-bruxas' }],
    events: ['Defesa de Sylvaris', 'Nomeação como Cavaleiro de Honra', 'Pacto dos Descendentes', 'Fuga para a Floresta Antiga'],
    curiosities: ['Foi o único não elfo a receber o título de Cavaleiro de Honra de Sylvaris.', 'Deixou a Sirius espada, carta, ouro, medalhão élfico e pertences de viagem.'],
    quotes: ['Poder sem limite não existe. Existe apenas alguém que decidiu fazer outro pagar o custo.'],
  }),
  record({
    id: 'namidia-bellatrix', name: 'Namídia Bellatrix', subtitle: 'Princesa da fortaleza rebelde',
    summary: 'Líder das Montanhas Cinzentas que acolheu Normus, tornou-se sua companheira e morreu protegendo o filho Sirius.',
    description: 'Namídia cresceu administrando estoques de cerco, rotas de fuga e alianças entre fortalezas que desconfiavam umas das outras. O título de princesa dos Bellatrix significava responsabilidade, não luxo. Ela se apaixonou por Normus ao perceber que o bruxo mais poderoso do continente ainda pedia permissão antes de agir em território rebelde. Fugiu com ele e morreu mantendo os perseguidores longe de Sirius.',
    image: '/assets/images/characters/namidia-bellatrix-v2-page.webp', thumbnail: '/assets/images/characters/namidia-bellatrix-v2-card.webp', accent: '#a65650', thumbnailPosition: 'center 18%', heroPosition: '64% 16%',
    category: 'Figura histórica', status: 'Morta — lendária', origin: 'Fortaleza do Véu', location: 'Montanhas Cinzentas', period: 'Caça às Bruxas', race: 'Humana', lineage: 'Bellatrix', genealogyId: 'bellatrix',
    appearance: 'Pele morena; cabelos negros parcialmente trançados; olhos castanhos; cicatriz fina na sobrancelha; vestes práticas de liderança rebelde.',
    objectives: ['Manter a Fortaleza do Véu aberta a perseguidos', 'Unir fortalezas sem criar outra coroa', 'Garantir que Sirius sobrevivesse sem se tornar propriedade política'],
    fears: ['Que a resistência reproduzisse a tirania combatida', 'Que cifras e segredos apagassem as pessoas que deveriam proteger'],
    flaws: ['Aceitava riscos pessoais extremos para não transferi-los a subordinados', 'Podia transformar responsabilidade em recusa de ajuda'],
    beliefs: ['A Chama sem Coroa', 'Juramento ao povo supera juramento ao trono'],
    equipment: ['Caderno cifrado de abastecimento', 'Espada curta de defesa', 'Fivelas de mensageiros para rotas de fuga'],
    abilities: ['Estratégia de cerco', 'Negociação entre fortalezas', 'Combate defensivo', 'Criptografia Bellatrix'],
    limitations: ['Não possuía magia verdadeira', 'Sofria com uma lesão antiga no ombro', 'Seu título dependia da confiança dos vigias'],
    relations: [{ label: 'Normus Kayler — companheiro', to: '/personagens/normus-kayler' }, { label: 'Sirius Kayler — filho', to: '/personagens/sirius-kayler' }, { label: 'Casa Bellatrix', to: '/casas/bellatrix' }],
    events: ['Acolhimento de Normus', 'Fuga para a Floresta Antiga', 'Sacrifício pela sobrevivência de Sirius'],
    curiosities: ['Suas cifras usavam variações de inventários de grãos para ocultar nomes.'],
    quotes: ['Abrigo não é o lugar onde o medo termina. É onde ninguém precisa enfrentá-lo sozinho.'],
  }),
  record({
    id: 'elara', name: 'Elara', subtitle: 'A herdeira do caminho oculto',
    summary: 'Jovem princesa élfica, guerreira, sobrinha da Rainha de Sylvaris e portadora de uma adaga rúnica de teletransporte.',
    description: 'Elara foi educada para governar um reino que considera memória e ecologia partes da mesma lei. Sua baixa estatura nunca limitou sua presença no campo. A adaga rúnica abre saltos breves entre pontos que ela consiga ver ou tenha marcado previamente; cada uso drena calor corporal e pode deixá-la desorientada. O pacto feito por sua tia e Normus liga seu futuro ao de Sirius, mas não determina seus sentimentos nem suas escolhas.',
    image: '/assets/images/characters/elara-page.webp', thumbnail: '/assets/images/characters/elara-card.webp', accent: '#b9b66d', thumbnailPosition: 'center 24%', heroPosition: '63% 20%',
    category: 'Herdeira', status: 'Viva', origin: 'Lethariel', location: 'Floresta Antiga', period: 'Era atual', race: 'Elfa', kingdom: 'Sylvaris', age: 'equivalente a cerca de 19 anos humanos', genealogyId: 'real-sylvaris',
    appearance: 'Caçula de três princesas; cabelos loiros; olhos dourados; baixa estatura; orelhas élficas; roupas funcionais de guerreira e princesa.',
    objectives: ['Ser reconhecida por escolhas, não apenas pelo pacto herdado', 'Preparar-se para governar sem tratar a floresta como recurso da coroa', 'Descobrir por que a tia protege um herdeiro Kayler que ela ainda não conhece no início da saga'],
    fears: ['Que Aelysar e o trono substituam sua liberdade por função', 'Que a adaga falhe com outra pessoa em trânsito'],
    flaws: ['Teimosia diante de autoridade que não explicou seus motivos', 'Age antes de pedir apoio quando acredita que o conselho demorará'],
    beliefs: ['A floresta participa das decisões', 'Juramentos herdados só valem quando escolhidos'],
    equipment: ['Adaga do Passo Velado', 'Marcadores de prata para rotas seguras', 'Aelysar será entregue apenas no trono'],
    abilities: ['Combate com adaga', 'Teletransporte rúnico de curto alcance', 'Rastreamento florestal', 'Diplomacia de Sylvaris'],
    limitations: ['Saltos exigem concentração, esforço físico e visão ou marca prévia', 'O destino precisa oferecer uma área segura de chegada', 'A adaga não corrige um ponto de pouso perigoso', 'Uso repetido causa hipotermia e vertigem', 'Não atravessa barreiras de ferro meteórico'],
    relations: [{ label: 'Rainha Aelwen — tia', to: '/personagens/rainha-aelwen' }, { label: 'Sirius Kayler — aliado ligado pelo pacto', to: '/personagens/sirius-kayler' }, { label: 'Genealogia real', to: '/personagens/elara/genealogia' }, { label: 'Sucessão de Sylvaris', to: '/sucessoes/sylvaris' }, { label: 'Sylvaris', to: '/reinos/sylvaris' }, { label: 'Aelysar', to: '/reliquias/aelysar' }],
    events: ['Juramento da Herdeira', 'Primeiro salto além de Sylvaris', 'Encontro com Sirius'],
    curiosities: ['Marca rotas seguras com fios de prata quase invisíveis.'],
    quotes: ['Um juramento herdado ainda precisa ser escolhido por quem o carrega.'],
  }),
  record({
    id: 'rainha-aelwen', name: 'Rainha Aelwen', subtitle: 'Guardadora da Memória de Sylvaris',
    summary: 'Soberana élfica, tia de Elara, grande amiga de Normus e guardiã do pacto secreto firmado com ele.',
    description: 'Aelwen governa por escuta e demora calculada, métodos que estrangeiros confundem com hesitação. Durante a Caça às Bruxas, abriu caminhos de Sylvaris para refugiados e aceitou o risco de proteger o filho de Normus. A amizade entre os dois nasceu no campo de batalha e permaneceu inteiramente fraterna e política.',
    image: '/assets/images/characters/rainha-sylvaris-page.webp', thumbnail: '/assets/images/characters/rainha-sylvaris-card.webp', accent: '#86a66f', thumbnailPosition: 'center 17%', heroPosition: '62% 18%',
    category: 'Soberana', status: 'Viva', origin: 'Lethariel', location: 'Sylvaris', period: 'Era das Coroas / Era atual', race: 'Elfa', kingdom: 'Sylvaris', genealogyId: 'real-sylvaris',
    appearance: 'Cabelos dourados; olhos castanho-dourados; postura madura; trajes verdes e marfim de construção vegetal.',
    objectives: ['Preparar Elara para escolher a sucessão conscientemente', 'Cumprir o pacto com Normus sem governar Sirius', 'Evitar que o segredo divida os Círculos da Memória'],
    fears: ['Que a proteção se transforme em tutela', 'Que revelar o pacto cedo demais provoque outra perseguição'],
    flaws: ['A demora calculada pode negar informação a quem precisa decidir', 'Carrega sozinha parte excessiva do pacto'],
    beliefs: ['Amizade e lealdade não implicam romance', 'Uma coroa é função limitada pela memória coletiva'],
    abilities: ['Diplomacia', 'Memória ritual élfica', 'Comando das sentinelas', 'Arqueira cerimonial'],
    limitations: ['Sua autoridade é limitada pelos Círculos da Memória', 'O pacto com Normus divide seu conselho'],
    relations: [{ label: 'Elara — sobrinha e herdeira', to: '/personagens/elara' }, { label: 'Normus Kayler — amigo e aliado', to: '/personagens/normus-kayler' }, { label: 'Sylvaris', to: '/reinos/sylvaris' }, { label: 'Sucessão de Sylvaris', to: '/sucessoes/sylvaris' }],
    events: ['Defesa de Sylvaris', 'Pacto dos Descendentes', 'Abrigo de Sirius'],
    quotes: ['Guardar um segredo é também responder pelo que ele impede o mundo de escolher.'],
  }),
  record({
    id: 'ilyra-arden', name: 'Ilyra Arden', subtitle: 'Capitã dos Campos Baixos',
    summary: 'Herdeira valoriana que protege diques e comboios enquanto enfrenta a ala expansionista da própria família.',
    description: 'Ilyra ganhou autoridade durante uma inundação, coordenando camponeses e cavalaria sem esperar ordens da corte. Sua popularidade ameaça parentes que lucram com escassez artificial. Ela vê em Sirius uma possível proteção para o continente, mas recusa transformar um homem em arma de Estado.',
    image: '/assets/images/characters/guerreira-ruiva-page.webp', thumbnail: '/assets/images/characters/guerreira-ruiva-card.webp', accent: '#b36f4f', thumbnailPosition: 'center 18%', heroPosition: '62% 17%',
    category: 'Nobre guerreira', status: 'Viva', origin: 'Valóris', location: 'Valoria', period: 'Era atual', race: 'Humana', lineage: 'Arden', kingdom: 'Valoria', genealogyId: 'valoria',
    abilities: ['Espada longa', 'Cavalaria', 'Logística fluvial'], limitations: ['Sem magia', 'Responsável por comunidades vulneráveis'],
    relations: [{ label: 'Casa Arden', to: '/casas/arden' }, { label: 'Valoria', to: '/reinos/valoria' }],
    quotes: ['O campo não alimenta uma coroa. Alimenta pessoas.'],
  }),
  record({
    id: 'kharza-gron', name: 'Kharza Gron', subtitle: 'Emissária de Vul’Gar',
    summary: 'Comandante orc enviada para impedir que Ravenhold transforme disputas de fronteira em guerra total.',
    description: 'Kharza pertence a um povo dividido em clãs, cidades e tradições — não a uma horda única. Ela negociou corredores de água durante secas e combateu chefes que lucravam com saques. Sua missão em Avernor é provar que Vul’Gar pode firmar tratados sem apagar sua autonomia.',
    image: '/assets/images/characters/guerreira-orc-page.webp', thumbnail: '/assets/images/characters/guerreira-orc-card.webp', accent: '#8d9c65', thumbnailPosition: 'center 18%', heroPosition: '61% 18%',
    category: 'Emissária', status: 'Viva', origin: 'Vul’Gar', location: 'Fronteira oriental', period: 'Era atual', race: 'Orc', genealogyId: 'gron',
    abilities: ['Diplomacia de clãs', 'Machado curto', 'Táticas de infantaria'], limitations: ['Sem magia', 'Autoridade limitada fora de seus clãs signatários'],
    relations: [{ label: 'Ravenhold', to: '/reinos/ravenhold' }, { label: 'Gorvak Tor', to: '/personagens/gorvak-tor' }],
    quotes: ['Paz não é silêncio. É a discussão continuar sem que enterremos os interlocutores.'],
  }),
  record({
    id: 'gorvak-tor', name: 'Gorvak Tor', subtitle: 'Guardião da Estrada de Cinza',
    summary: 'Veterano orc responsável por comboios entre os poços de Vul’Gar e a fronteira de Ravenhold.',
    description: 'Gorvak perdeu dois irmãos para cobradores que falsificavam bandeiras dos dois lados. Desde então, protege mercadores e mantém um registro público de ataques. Seu tamanho inspira medo; sua principal arma, porém, é a reputação de cumprir acordos literais.',
    image: '/assets/images/characters/guerreiro-orc-page.webp', thumbnail: '/assets/images/characters/guerreiro-orc-card.webp', accent: '#8a765d', thumbnailPosition: 'center 17%', heroPosition: '61% 17%',
    category: 'Guardião de estrada', status: 'Vivo', origin: 'Vul’Gar', location: 'Fronteira oriental', period: 'Era atual', race: 'Orc', genealogyId: 'tor',
    abilities: ['Defesa de comboios', 'Rastreamento em terreno árido', 'Combate com maça'], limitations: ['Visão reduzida no olho esquerdo', 'Sem autoridade política formal'],
    relations: [{ label: 'Kharza Gron', to: '/personagens/kharza-gron' }],
    quotes: ['Se uma estrada não é segura para o menor carro, ela não pertence a povo algum.'],
  }),
]

export const characters = characterRecords.map((character) => ({ ...character, ...characterDossiers[character.id] }))
