import { record } from '../schema.js'
import { cityDossiers } from '../places/dossiers.js'

const cityRecords = [
  record({ id: 'winterheim', name: 'Winterheim', subtitle: 'A cidadela sob o gelo', summary: 'Capital de Winterfeld, erguida em terraços de pedra negra ao redor de fontes termais.', description: 'Canais aquecidos mantêm oficinas e enfermarias funcionando durante o inverno. A cidade fecha seus portões externos por quarenta noites no auge do frio, mas conserva túneis de socorro conhecidos por guias juramentados.', category: 'Capital', status: 'Habitada', kingdom: 'Winterfeld', location: 'Winterfeld', population: '38 mil habitantes', economy: 'Metalurgia, peles e abastecimento militar', relations: [{ label: 'Winterfeld', to: '/reinos/winterfeld' }] }),
  record({ id: 'lethariel', name: 'Lethariel', subtitle: 'A cidade entre raízes e estrelas', summary: 'Capital de Sylvaris, distribuída entre margens, plataformas vivas e salões escavados sem ferir as árvores.', description: 'Lethariel não possui muralha convencional. Trilhas mudam, pontes são recolhidas e sentinelas leem alterações no comportamento de aves e fungos. O Palácio da Seiva Clara guarda o pacto firmado entre Normus e a Rainha.', category: 'Capital', status: 'Habitada', kingdom: 'Sylvaris', location: 'Floresta Antiga', population: '22 mil habitantes', economy: 'Cura, manuscritos, vidro vegetal e diplomacia', image: '/assets/images/atlas-plates/lethariel-page.webp', thumbnail: '/assets/images/atlas-plates/lethariel-card.webp', relations: [{ label: 'Sylvaris', to: '/reinos/sylvaris' }, { label: 'Elara', to: '/personagens/elara' }] }),
  record({ id: 'thur-kar', name: 'Thur-Kar', subtitle: 'O salão das nove bigornas', summary: 'Centro político de Kar-Dûm e ponto de encontro entre nove redes subterrâneas.', description: 'Pontes de pedra cruzam um vazio iluminado por canais de magma controlados. A ventilação da cidade é uma obra tão valorizada quanto suas forjas: qualquer mestre que a comprometa perde o direito de trabalhar metal.', category: 'Capital subterrânea', status: 'Habitada', kingdom: 'Kar-Dûm', location: 'Cordilheira central', population: '61 mil habitantes', economy: 'Forjas, bombas hidráulicas e cartografia subterrânea', relations: [{ label: 'Kar-Dûm', to: '/reinos/kar-dum' }] }),
  record({ id: 'valoris', name: 'Valóris', subtitle: 'Mercado das sete pontes', summary: 'Capital de Valoria, cortada por canais de irrigação e dominada por celeiros fortificados.', description: 'A praça central funciona ao mesmo tempo como mercado, bolsa de grãos e tribunal de pesos. Nos bairros baixos, associações de barqueiros exercem poder equivalente ao das famílias nobres.', category: 'Capital', status: 'Habitada', kingdom: 'Valoria', location: 'Planícies centrais', population: '94 mil habitantes', economy: 'Grãos, crédito e transporte fluvial', relations: [{ label: 'Valoria', to: '/reinos/valoria' }, { label: 'Casa Arden', to: '/casas/arden' }] }),
  record({ id: 'ravencastle', name: 'Ravencastle', subtitle: 'A fortaleza que virou cidade', summary: 'Capital escalonada de Ravenhold, organizada ao redor de antigos anéis defensivos.', description: 'Cada expansão preservou a muralha anterior, criando bairros circulares e gargalos fáceis de defender. A arquitetura oferece segurança, mas concentra multidões e torna incêndios um risco constante.', category: 'Capital fortificada', status: 'Habitada', kingdom: 'Ravenhold', location: 'Leste central', population: '73 mil habitantes', economy: 'Armas, logística e administração militar', relations: [{ label: 'Ravenhold', to: '/reinos/ravenhold' }] }),
  record({ id: 'porto-de-eldemar', name: 'Porto de Eldemar', subtitle: 'A cidade das pontes móveis', summary: 'Capital marítima construída sobre ilhas rochosas, docas profundas e pontes que isolam distritos durante ataques.', description: 'O nível inferior pertence às marés e recebe armazéns de pedra; residências ocupam terraços superiores. Sinos codificados anunciam tempestades, incêndios ou monstros marinhos sem causar pânico desnecessário.', category: 'Capital portuária', status: 'Habitada', kingdom: 'Eldemar', location: 'Costa sul', population: '81 mil habitantes', economy: 'Estaleiros, sal, pesca e cartografia', relations: [{ label: 'Eldemar', to: '/reinos/eldemar' }] }),
  record({ id: 'fortaleza-do-veu', name: 'Fortaleza do Véu', subtitle: 'Pedra para quem ficou sem bandeira', summary: 'Maior reduto das Montanhas Cinzentas e antiga residência da família Bellatrix.', description: 'Escavada atrás de uma queda-d’água sazonal, a fortaleza possui depósitos dispersos para resistir a cercos. Seus arquivos registram nomes verdadeiros apenas em cifras, protegendo descendentes de perseguidos.', category: 'Fortaleza', status: 'Habitada', kingdom: 'Montanhas Cinzentas', location: 'Montanhas Cinzentas', population: '9 mil habitantes', economy: 'Escolta, mineração, criação e pedágios', relations: [{ label: 'Montanhas Cinzentas', to: '/reinos/montanhas-cinzentas' }, { label: 'Namídia Bellatrix', to: '/personagens/namidia-bellatrix' }] }),
  record({ id: 'porto-verde', name: 'Porto Verde', subtitle: 'A margem aberta de Sylvaris', summary: 'Entreposto controlado onde estrangeiros negociam com Sylvaris sem penetrar os bosques internos.', description: 'Armazéns repousam sobre estacas para não alterar o curso das águas. Mercadores entregam armas na entrada e recebem fichas de madeira numeradas; qualquer fraude encerra o acesso de toda a companhia por uma estação.', category: 'Porto fluvial', status: 'Habitada', kingdom: 'Sylvaris', location: 'Costa oeste', population: '7 mil habitantes', economy: 'Troca de ervas, vidro, tecidos e mapas', relations: [{ label: 'Sylvaris', to: '/reinos/sylvaris' }] }),
]

export const cities = cityRecords.map((city) => ({ ...city, ...cityDossiers[city.id] }))
